  "mem="CONFIG_MEM"\0"                              
  "phym="CONFIG_PHYM"\0"                            
  "ipaddr=" CONFIG_IP_ADDRESS "\0"                  
  "serverip=" CONFIG_SERVER_IP_ADDRESS "\0"         
  "ethaddr=" CONFIG_ETHERNET_ADDRESS "\0"           
  "netdev=" CONFIG_ETHERNET_DEVICE "\0"             
  "console="CONFIG_CONSOLE"\0"                      
  "baudrate=" CONFIG_ASC_BAUDRATE "\0"              
  "tftppath="CONFIG_TFTPPATH"\0"                    
  "loadaddr=" CONFIG_TFTP_LOAD_ADDRESS "\0"         
  "rootpath="CONFIG_ROOT_PATH "\0"                  
  "rootfsmtd="CONFIG_ROOTFSMTD"\0"                  
  "nfsargs= "CONFIG_NFSARGS"\0"                     
  "ramargs="CONFIG_RAMARGS"\0"                      
  "addip="CONFIG_ADDIP"\0"                          
  "addmisc="CONFIG_ADDMISC" \0"                     
  "flash_nfs="CONFIG_FLASH_NFS"\0"                  
  "net_nfs="CONFIG_NET_NFS"\0"                      
  "net_flash="CONFIG_NET_FLASH"\0"                  
  "net_ram="CONFIG_NET_RAM"\0"                      
  "u-boot="CONFIG_U_BOOT"\0"                        
  "rootfs="CONFIG_ROOTFS"\0"                        
  "firmware="CONFIG_FIRMWARE"\0"                    
  "fullimage="CONFIG_FULLIMAGE"\0"                  
  "totalimage="CONFIG_TOTALIMAGE"\0"                
  "load=tftp $(loadaddr) $(u-boot)\0"               
  "update=protect off 1:0-2;era 1:0-2;cp.b $(loadaddr) B0000000 $(filesize)\0"  
  "flashargs="CONFIG_FLASHARGS"\0"                  
  "flash_flash="CONFIG_FLASH_FLASH"\0"              
#ifdef CONFIG_BOOT_FROM_NAND  
  "update_nandboot="CONFIG_UPDATE_NANDBOOT"\0"
#endif
  "update_uboot="CONFIG_UPDATE_UBOOT"\0"            
  "update_kernel="CONFIG_UPDATE_KERNEL"\0"          
  "update_rootfs="CONFIG_UPDATE_ROOTFS"\0"          
  "update_firmware="CONFIG_UPDATE_FIRMWARE"\0"      
  "update_fullimage="CONFIG_UPDATE_FULLIMAGE"\0"    
  "update_totalimage="CONFIG_UPDATE_TOTALIMAGE"\0"  
#ifndef CONFIG_ENV_IS_NOWHERE 
  "reset_uboot_config="CONFIG_RESET_UBOOT_CONFIG"\0" 
  "reset_ddr_config="CONFIG_RESET_DDR_CONFIG"\0" 
  "mtdparts="CONFIG_MTDPARTS"\0"                     
  IFX_CFG_FLASH_PARTITIONS_INFO   
  "flash_end=" MK_STR(IFX_CFG_FLASH_END_ADDR) "\0"   
  IFX_CFG_FLASH_DATA_BLOCKS_INFO  
  "f_uboot_addr=" MK_STR(IFX_CFG_FLASH_UBOOT_IMAGE_START_ADDR) "\0"      
  "f_uboot_size=" MK_STR(IFX_CFG_FLASH_UBOOT_IMAGE_SIZE) "\0"            
  "f_ubootconfig_addr=" MK_STR(IFX_CFG_FLASH_UBOOT_CFG_START_ADDR) "\0"  
  "f_ubootconfig_size=" MK_STR(IFX_CFG_FLASH_UBOOT_CFG_SIZE) "\0"        
  "f_ubootconfig_end=" MK_STR(IFX_CFG_FLASH_UBOOT_CFG_END_ADDR) "\0"     
  "f_kernel_addr=" MK_STR(IFX_CFG_FLASH_KERNEL_IMAGE_START_ADDR) "\0"    
  "f_kernel_size=" MK_STR(IFX_CFG_FLASH_KERNEL_IMAGE_SIZE) "\0"          
  "f_kernel_end=" MK_STR(IFX_CFG_FLASH_KERNEL_IMAGE_END_ADDR) "\0"       
  "f_rootfs_addr=" MK_STR(IFX_CFG_FLASH_ROOTFS_IMAGE_START_ADDR) "\0"    
  "f_rootfs_size=" MK_STR(IFX_CFG_FLASH_ROOTFS_IMAGE_SIZE) "\0"          
  "f_rootfs_end=" MK_STR(IFX_CFG_FLASH_ROOTFS_IMAGE_END_ADDR) "\0"       
#ifndef CONFIG_FIRMWARE_IN_ROOTFS  
  "f_firmware_addr=" MK_STR(IFX_CFG_FLASH_FIRMWARE_IMAGE_START_ADDR) "\0" 
  "f_firmware_size=" MK_STR(IFX_CFG_FLASH_FIRMWARE_IMAGE_SIZE) "\0"       
#endif
  "f_sysconfig_addr=" MK_STR(IFX_CFG_FLASH_SYSTEM_CFG_START_ADDR) "\0"    
  "f_sysconfig_size=" MK_STR(IFX_CFG_FLASH_SYSTEM_CFG_SIZE) "\0"          
  "f_fwdiag_addr=" MK_STR(IFX_CFG_FLASH_FIRMWARE_DIAG_START_ADDR) "\0"    
  "f_fwdiag_size=" MK_STR(IFX_CFG_FLASH_FIRMWARE_DIAG_SIZE) "\0"          
  "f_calibration_addr= " MK_STR(IFX_CFG_FLASH_CALIBRATION_START_ADDR) "\0"  
  "f_calibration_size=" MK_STR(IFX_CFG_FLASH_CALIBRATION_CFG_SIZE) "\0"   
  "f_ddrconfig_addr=" MK_STR(IFX_CFG_FLASH_DDR_CFG_START_ADDR) "\0"       
  "f_ddrconfig_size=" MK_STR(IFX_CFG_FLASH_DDR_CFG_SIZE) "\0"             
  "f_ddrconfig_end=" MK_STR(IFX_CFG_FLASH_DDR_CFG_END_ADDR) "\0"          
#ifdef CONFIG_OVERLAY
  "f_overlay_addr=" MK_STR(IFX_CFG_FLASH_OVERLAY_IMAGE_START_ADDR) "\0"       
  "f_overlay_size=" MK_STR(IFX_CFG_FLASH_OVERLAY_IMAGE_SIZE) "\0"             
  "f_overlay_end=" MK_STR(IFX_CFG_FLASH_OVERLAY_IMAGE_END_ADDR) "\0"   
#endif
#endif
  "" 
