#OpenRG: This file was automatically generated by pkg/build/create_config
#See /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/config.log for configuration log.

# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:988
CONFIG_RG_ETHOA_DEV_NAME=ethoa0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:989
CONFIG_RG_PPPOA_DEV_NAME=ppp0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:990
CONFIG_RG_PPPOE_DEV_NAME=ppp1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:991
CONFIG_RG_PPPOEOA_DEV_NAME=ppp2
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:992
CONFIG_RG_PPPOEOP_DEV_NAME=ppp3
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:993
CONFIG_RG_WAN_ETH_DEV_NAME=eth1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:994
CONFIG_RG_WAN_ETHOA_DEV_NAME=ethoa1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:868
CONFIG_BOOTLDR_UBOOT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:869
CONFIG_BOOTLDR_UBOOT_COMP=lzma
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:987
CONFIG_BOOTLDR_UBOOT_SIGNED_IMAGES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:988
CONFIG_BOOTLDR_UBOOT_SECURED_BOOT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:870
CONFIG_HOST_LZMA_PATH=vendor/lantiq/xway/u-boot/tools
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2405
CONFIG_SILENT_CONSOLE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:989
CONFIG_BOOTLDR_UBOOT_SECURED_ENV=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2406
CONFIG_BOOTLDR_UBOOT_ENV_ACCESS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:883
export RG_PROD_STR=BT Home Hub 5.0A
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:42
export CONFIG_RG_OS=LINUX_26
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:271
export CONFIG_RG_HW=SAGEM_HH5_VRX268
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4318
RMT_UPG_SITE=update.jungo.com
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4321
RMT_UPG_URL=https://update.jungo.com/
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:272
CONFIG_RG_HW_DESC_STR=BT Home Hub 5 - Sagem platform
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:6198
CONFIG_RG_DIST=SAGEM_HH5
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:951
CONFIG_RG_WIRELESS_COUNTRY_CODE=GB
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:94
CONFIG_MMU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1887
CONFIG_BROKEN_ON_SMP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:78
CONFIG_INIT_ENV_ARG_LIMIT=32
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:79
CONFIG_PRINTK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:81
CONFIG_BUG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:82
CONFIG_TINY_SHMEM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:83
CONFIG_BASE_SMALL=0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:121
CONFIG_OBSOLETE_MODPARM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:122
CONFIG_KMOD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1882
CONFIG_GENERIC_CALIBRATE_DELAY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:95
CONFIG_IOSCHED_NOOP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:96
CONFIG_IOSCHED_AS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:97
CONFIG_IOSCHED_DEADLINE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:98
CONFIG_IOSCHED_CFQ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:100
CONFIG_DEFAULT_IOSCHED="anticipatory"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:196
CONFIG_NET_IPGRE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:194
CONFIG_INET_TUNNEL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:137
CONFIG_XFRM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:138
CONFIG_NET_SCH_CLK_JIFFIES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:142
CONFIG_LEGACY_PTYS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:143
CONFIG_LEGACY_PTY_COUNT=256
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2227
CONFIG_LOG_BUF_SHIFT=14
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3542
CONFIG_CRC16=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3543
CONFIG_CRC32=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4371
CONFIG_GENERIC_HARDIRQS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:120
CONFIG_MODULE_UNLOAD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1817
CONFIG_IRQ_CPU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3781
CONFIG_INITRAMFS_SOURCE=$(RAMDISK_MOUNT_POINT)
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3782
CONFIG_INITRAMFS_ROOT_UID=$(shell id -u)
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3783
CONFIG_INITRAMFS_ROOT_GID=$(shell id -g)
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:132
CONFIG_IP_FIB_HASH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2224
CONFIG_TRAD_SIGNALS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:822
CONFIG_RG_JPKG_DIST=JPKG_MIPSEB_XWAY_VRX
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2181
export ARCH=mips
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2182
export LIBC_ARCH=mips
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:239
CONFIG_DEBUG_INFO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:874
CONFIG_NETFILTER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4499
CONFIG_EXPORT_BINARIES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:370
CONFIG_RG_RGLOADER_CLI_CMD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:900
CONFIG_RG_UIEVENTS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:901
CONFIG_RG_KLEDS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:506
CONFIG_ATM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:513
CONFIG_ATM_BR2684=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:512
CONFIG_ATM_SKB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:507
CONFIG_ATM_PVC_SCAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:975
CONFIG_RG_ATM_QOS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:998
CONFIG_PTM_VLAN_DEV_NAME=ptm0.101
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:906
CONFIG_PTM_VLAN_ID=101
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:255
CONFIG_AUTO_LEARN_DNS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1889
CONFIG_BINFMT_ELF=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3826
CONFIG_BLK_DEV_INITRD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1888
CONFIG_BLK_DEV_LOOP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:876
CONFIG_CMDLINE=console=ttyS0,115200
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3804
export CONFIG_CRAMFS_DYN_BLOCKSIZE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3819
export CONFIG_CRAMFS_BLKSZ=65536
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2231
CONFIG_CPU_BIG_ENDIAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2178
CONFIG_CPU_MIPS32=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3800
CONFIG_CRAMFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3791
export CONFIG_CRAMFS_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3798
CONFIG_CRAMFS_FS_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:975
export CONFIG_UBIFS_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3538
CONFIG_UBIFS_FS_LZO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3540
CONFIG_UBIFS_FS_ZLIB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:872
BOOTLOADER_ADDR_SPACE_IS_VIRTUAL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2242
CONFIG_CROSSCOMPILE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:946
CONFIG_RG_WIRELESS_TOOLS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3825
CONFIG_DEBUG_USER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1324
CONFIG_DEF_KEYS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:874
CONFIG_DYN_LINK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4193
CONFIG_ULIBC_SHARED=y
# Set by command line:
LIC=/media/data/build/router/bt_hh5a_rg-4.7.5.1/jpkg_sagem_homehub5_vrx.lic.gpl
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1879
CONFIG_EXPERIMENTAL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:629
export CONFIG_EXT2_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:630
CONFIG_EXT3_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:631
CONFIG_JBD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:633
CONFIG_HFSPLUS_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:634
CONFIG_HFS_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:635
CONFIG_XFS_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:641
CONFIG_FUSE_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:955
CONFIG_MAGIC_SYSRQ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2491
CONFIG_FREEPAGES_HIGH=384
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2490
CONFIG_FREEPAGES_LOW=256
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2489
CONFIG_FREEPAGES_MIN=32
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4519
CONFIG_FREEPAGES_THRESHOLD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:657
CONFIG_FREESWAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2520
CONFIG_RG_NETBIOS_RT=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2472
CONFIG_GEN_RG_DEFAULT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2502
CONFIG_GMP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2176
CONFIG_HAS_MMU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:130
CONFIG_INET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:846
CONFIG_IP_ADVANCED_ROUTER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:131
CONFIG_IP_MULTICAST=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2503
CONFIG_IPSEC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2506
CONFIG_IPSEC_AH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2507
CONFIG_IPSEC_AUTH_HMAC_MD5=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2544
CONFIG_IPSEC_ALG_MD5=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2508
CONFIG_IPSEC_AUTH_HMAC_SHA1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2546
CONFIG_IPSEC_ALG_SHA1=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2516
CONFIG_IPSEC_DEBUG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2511
CONFIG_IPSEC_ENC_3DES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2538
CONFIG_IPSEC_ALG_3DES=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2510
CONFIG_IPSEC_ENC_1DES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2536
CONFIG_IPSEC_ALG_1DES=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2512
CONFIG_IPSEC_ENC_NULL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2540
CONFIG_IPSEC_ALG_NULL=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2541
CONFIG_IPSEC_ENC_AES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2542
CONFIG_IPSEC_ALG_AES=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2509
CONFIG_IPSEC_ESP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2513
CONFIG_IPSEC_IPCOMP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2505
CONFIG_IPSEC_IPIP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2521
CONFIG_RG_IPSEC_NO_SECRET_FILE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2504
CONFIG_IPSEC_DRIVER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2533
CONFIG_RG_IPSEC_ESP_ALG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2523
CONFIG_RG_IPSEC_IKE_ALG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2534
CONFIG_IPSEC_ALG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3998
CONFIG_LOG_FILES_MAX_SIZE=16384
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3997
CONFIG_LOG_FILES_MIN_SIZE=12288
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2100
CONFIG_MIPS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2237
CONFIG_MIPS32=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1883
CONFIG_SCHED_NO_NO_OMIT_FRAME_POINTER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1812
CONFIG_HZ_100=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1813
CONFIG_HZ=100
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1804
CONFIG_CPU_MIPS32_R2=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4398
CONFIG_MTD_NAND=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4399
CONFIG_MTD_NAND_IDS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:620
CONFIG_HOTPLUG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4456
export CONFIG_UEVENT_HELPER_PATH=
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4462
CONFIG_RG_NETLINK_HOTPLUG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:107
CONFIG_RAMFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:118
CONFIG_MODULES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:112
CONFIG_SYSFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:942
CONFIG_KEYS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:943
CONFIG_KEYS_DEBUG_PROC_KEYS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:944
CONFIG_SECURITY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4450
CONFIG_CRYPTO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4206
CONFIG_CRYPTO_HMAC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4207
CONFIG_CRYPTO_MD5=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4208
CONFIG_CRYPTO_AES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4451
CONFIG_CRYPTO_ALGAPI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4204
CONFIG_CRYPTO_HASH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:933
CONFIG_CRYPTO_BLKCIPHER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:937
CONFIG_CRYPTO_ECB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:935
CONFIG_CRYPTO_MANAGER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:938
CONFIG_CRYPTO_CBC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3539
CONFIG_CRYPTO_LZO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3541
CONFIG_CRYPTO_DEFLATE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1892
export CONFIG_MTD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3515
CONFIG_MTD_BLOCK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3516
CONFIG_MTD_BLKDEVS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3517
CONFIG_MTD_CFI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1901
CONFIG_MTD_CFI_INTELEXT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4400
CONFIG_MTD_CHAR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3518
CONFIG_MTD_GEN_PROBE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3514
CONFIG_MTD_PARTITIONS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1896
CONFIG_MTD_MAP_BANK_WIDTH_1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1897
CONFIG_MTD_MAP_BANK_WIDTH_2=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1898
CONFIG_MTD_MAP_BANK_WIDTH_4=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1899
CONFIG_MTD_CFI_I1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1900
CONFIG_MTD_CFI_I2=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1902
CONFIG_MTD_CFI_AMDSTD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1904
CONFIG_MTD_COMPLEX_MAPPINGS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1903
CONFIG_MTD_CFI_UTIL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1893
CONFIG_MTD_SLRAM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1947
CONFIG_RG_MTD_PARTS="mtdparts=ifx_nand:0x00100000@0(uboot),0x07e80000@0x00100000(UBI)"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:986
CONFIG_RG_MTD_NAND_PART=ifx_nand:0x00100000@0(uboot),0x07e80000@0x00100000(UBI)
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1895
CONFIG_MTD_CMDLINE_PARTS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:150
export CONFIG_MTD_UBI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3525
CONFIG_MTD_UBI_WL_THRESHOLD=4096
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3527
CONFIG_MTD_UBI_BEB_RESERVE=2
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3523
CONFIG_MTD_UBI_GLUEBI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:966
export CONFIG_RG_UBI_PARTITION_SIZE=0x7e80000
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:893
export CONFIG_HW_NAND_PEB_SIZE=0x20000
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:894
export CONFIG_HW_NAND_MIN_IO_SIZE=2048
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:895
export CONFIG_HW_NAND_SUB_PAGE_SIZE=512
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:126
CONFIG_NET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:127
CONFIG_NETDEVICES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:134
CONFIG_NET_ETHERNET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:189
CONFIG_NET_RADIO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:190
CONFIG_NET_WIRELESS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:192
CONFIG_WIRELESS_EXT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:195
CONFIG_NET_IPIP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:354
CONFIG_OPENRG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:374
CONFIG_RG_CONFIG_STRINGS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:128
CONFIG_PACKET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1040
CONFIG_PCI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1038
CONFIG_PCIEPORTBUS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1983
CONFIG_PCI_MSI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1969
CONFIG_IFX_PCI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1970
CONFIG_IFX_PCI_HW_SWAP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1971
CONFIG_IFX_PCI_CLOCK_DELAY_NANO_SECONDS=1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1972
CONFIG_IFX_PCI_CLOCK_DELAY_TENTH_NANO_SECOND=0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1976
CONFIG_IFX_PCIE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1981
CONFIG_IFX_PCIE_HW_SWAP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1039
CONFIG_IFX_PCIE_PHY_36MHZ_SSC_MODE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1977
CONFIG_IFX_PCIE_1ST_CORE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2517
CONFIG_PLUTO_DEBUG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:466
CONFIG_RG_PPP_COMMON=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:467
CONFIG_RG_PPP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:473
CONFIG_RG_PPP_BSDCOMP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:472
CONFIG_RG_PPP_DEFLATE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:482
CONFIG_RG_PPP_ON_DEMAND_DEFAULT_MAX_IDLE_TIME=1200
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:491
CONFIG_RG_PPP_DEFAULT_BSD_COMPRESSION=1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:500
CONFIG_RG_PPP_DEFAULT_DEFLATE_COMPRESSION=1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:515
CONFIG_RG_PPPOA=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:468
CONFIG_RG_PPPOE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1822
CONFIG_PROC_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:281
CONFIG_RG_ALG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:290
CONFIG_RG_ALG_ICMP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:291
CONFIG_RG_ALG_PORT_TRIGGER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:292
CONFIG_RG_ALG_FTP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:293
CONFIG_RG_PROXY_RTSP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:284
CONFIG_RG_ALG_H323=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3690
CONFIG_RG_ALG_SIP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:283
CONFIG_RG_ALG_MGCP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:287
CONFIG_RG_ALG_PPTP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:286
CONFIG_RG_ALG_MSNMS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:288
CONFIG_RG_ALG_IPSEC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:289
CONFIG_RG_ALG_L2TP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:285
CONFIG_RG_ALG_AIM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:334
CONFIG_RG_ALG_DNS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:335
CONFIG_RG_ALG_DHCP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3715
CONFIG_RG_ALG_USERSPACE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:269
CONFIG_RG_HYBRID_BRIDGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:275
CONFIG_RG_STP=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:268
CONFIG_RG_BRIDGE=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:527
CONFIG_RG_VLAN_BRIDGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:530
CONFIG_RG_8021Q_IF=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:822
CONFIG_RG_PSE=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:885
CONFIG_RG_PSE_PLAT_PATH=vendor/lantiq/xway/rg/modules
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:403
CONFIG_RG_CHRDEV=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:271
CONFIG_RG_USFS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:295
CONFIG_RG_PPPOE_RELAY=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:715
CONFIG_RG_DSLHOME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:748
CONFIG_RG_TR_098=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:793
CONFIG_RG_TR_064=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:113
CONFIG_RG_DSLHOME_OUI=X_0001E3_
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:205
CONFIG_RG_FIREWALL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:322
CONFIG_RG_ADV_SERVICES_LEVEL=2
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:160
CONFIG_RG_IGD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3664
CONFIG_RG_MGT_IGD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:312
CONFIG_RG_IGMP_PROXY=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3716
CONFIG_RG_JFW=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:298
CONFIG_RG_MSS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:392
CONFIG_RG_LAN_UPGRADE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:74
CONFIG_RG_OS_LINUX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:278
CONFIG_RG_NAT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3647
CONFIG_RG_OPENSSL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:904
CONFIG_RG_SMIME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3650
CONFIG_RG_CRYPTO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2410
CONFIG_RG_POLARSSL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:433
CONFIG_RG_SSL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4165
CONFIG_RG_PERM_STORAGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:958
export CONFIG_RG_PERM_STORAGE_UBI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:960
export CONFIG_RG_PERM_STORAGE_UBI_VOLUME_SIZE=0x281d000
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:967
export CONFIG_RG_CALDATA_VOLUME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3529
export CONFIG_RG_CALDATA_VOLUME_NAME=caldata
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:971
export CONFIG_RG_CALDATA_VOLUME_SIZE=0x001f800
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:972
export CONFIG_RG_CALDATA_DEV_MINOR=4
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:962
export CONFIG_RG_UBIFS_UBI_VOLUME_SIZE=0x5175000
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3545
export CONFIG_RG_UBIFS_UBI_VOLUME_NAME=FFS
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:149
CONFIG_RG_UBI_PARTITION=UBI
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:976
export CONFIG_RG_BT_FLASH_FS=/mnt/storage
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:978
export CONFIG_RG_UBIFS_MNT_DIR=ubifs
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:983
export CONFIG_RG_PRIVATE_FS_MNT_DIR=/mnt/private
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:977
export CONFIG_RG_PERMST_PARTITION=OpenRG
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:982
export CONFIG_RG_ENCRYPTED_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1025
CONFIG_RG_ONE_MODULE=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:365
CONFIG_RG_KOS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:366
CONFIG_RG_KOS_KNET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:413
CONFIG_RG_IPV4=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:173
CONFIG_RG_RIP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:177
CONFIG_RG_BGP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:178
CONFIG_RG_OSPF=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:394
CONFIG_RG_RMT_UPDATE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4326
CONFIG_RG_RMT_UPD_RSA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4327
CONFIG_RG_RMT_UPD_ANY_VERSION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4330
CONFIG_RG_RMT_UPGRADE_IMG_IN_MEM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:979
CONFIG_RG_RMT_UPD_ENC_IMG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:980
CONFIG_RG_ENC_IMG_IN_FLASH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:204
CONFIG_RG_RNAT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:398
CONFIG_RG_SYSINIT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4004
CONFIG_RG_SYSLOG_REMOTE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:733
CONFIG_RG_KNET_COUNTERS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3658
CONFIG_RG_UPNP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2420
CONFIG_RG_WAN_UPGRADE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:133
CONFIG_RG_WLAN_AUTO_CHANNEL_SELECT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:377
CONFIG_RG_DNS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:181
CONFIG_RG_DNS_CONCURRENT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:200
CONFIG_RG_DNS_ROUTE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:184
CONFIG_RG_DNS_DOMAIN_ROUTING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:384
CONFIG_RG_DDNS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:436
CONFIG_RG_ENTFY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2436
CONFIG_RG_HTTP_PROXY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3714
CONFIG_RG_GENERIC_PROXY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:701
CONFIG_RG_URL_KEYWORD_FILTER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:700
CONFIG_RG_SURFCONTROL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3624
CONFIG_RG_8021X=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3628
CONFIG_RG_8021X_PKTFIL=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:916
CONFIG_RG_8021X_RADIUS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3727
CONFIG_RG_8021X_WBM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1004
CONFIG_RG_RADIUS_CLIENT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:129
CONFIG_RG_VENDOR_WLAN_SEC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4224
CONFIG_RG_AUTH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:130
CONFIG_RG_RADIUS_WBM_IN_CONN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4366
CONFIG_RG_RADIUS_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:131
CONFIG_RG_WPA_WBM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:134
CONFIG_RG_WSEC_DAEMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:254
CONFIG_RG_DHCPS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:387
CONFIG_RG_DHCPC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:258
CONFIG_RG_DHCPR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3615
CONFIG_RG_DHCP_PKTFIL=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2421
CONFIG_RG_SSI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:339
CONFIG_RG_WBM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:743
CONFIG_RG_WBM_EXTERNAL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:169
CONFIG_RG_REDUCE_SUPPORT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:933
CONFIG_RG_TCPDUMP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4268
CONFIG_FREESWAN_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4280
CONFIG_RG_ACL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4279
CONFIG_RG_ATTR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4285
CONFIG_RG_BACKUP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4260
CONFIG_RG_DHCP_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:615
CONFIG_RG_DOSFSTOOLS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:640
CONFIG_RG_NTFSPROGS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:614
CONFIG_RG_E2FSPROGS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:618
CONFIG_RG_NTFS_3G=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4254
CONFIG_RG_LIBPCAP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3832
CONFIG_RG_PCAP_SOCKET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4249
CONFIG_RG_LZMA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4231
CONFIG_RG_MGT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4235
CONFIG_RG_OPENSSL_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4240
CONFIG_RG_OPENSSL_MD5=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4243
CONFIG_RG_OPENSSL_SHA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4244
CONFIG_RG_OPENSSL_DES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4245
CONFIG_RG_OPENSSL_MD4=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4239
CONFIG_RG_OPENSSL_AES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4308
CONFIG_RG_OPENSSL_BLOWFISH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4309
CONFIG_RG_OPENSSL_CAST=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4265
CONFIG_RG_RGLOADER_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4284
CONFIG_RG_STAR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4037
CONFIG_RG_SYSLOG_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4255
CONFIG_RG_TERMCAP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4275
CONFIG_RG_TEST_TOOLS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4230
CONFIG_RG_TZ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:616
CONFIG_RG_UTIL_LINUX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:110
CONFIG_GUI_BT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3681
CONFIG_RG_LIBIMAGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3674
CONFIG_RG_LIBIMAGE_DIM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3717
CONFIG_RG_NETOBJ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3703
CONFIG_RG_AUTO_DST=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:340
CONFIG_RG_TZ_COMMON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3705
CONFIG_RG_TZ_YEARS=7
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3684
CONFIG_RG_HTTPS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3687
CONFIG_HTTP_CGI_PROCESS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3995
CONFIG_RG_SYSLOG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4034
CONFIG_RG_SYSLOG_GLIBC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3996
CONFIG_RG_LOG_DEV=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4001
CONFIG_RG_KERN_LOG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4020
CONFIG_RG_LOG_DEV_BUF_SIZE=16384
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4021
CONFIG_RG_SYSLOG_FW_DEF_SIZE=16384
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:936
export CONFIG_RG_KLOG=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:937
CONFIG_RG_KLOG_RAMSIZE=0x40000
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4163
CONFIG_RG_CLI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4307
CONFIG_RG_CLI_SERVER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4170
CONFIG_RG_CLI_SERIAL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2228
CONFIG_RG_TTYP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:371
CONFIG_RG_LOGIN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:310
CONFIG_RG_STATIC_ROUTE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:407
CONFIG_RG_BUSYBOX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:378
CONFIG_RG_ERESOLV=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4172
CONFIG_RG_WGET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2518
CONFIG_RG_FREESWAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3633
CONFIG_RG_X509=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3637
CONFIG_RG_CERT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4162
CONFIG_RGLOADER_CLI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2240
CONFIG_RWSEM_GENERIC_SPINLOCK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:873
CONFIG_SDRAM_SIZE=128
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1830
CONFIG_SERIAL_CORE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1831
CONFIG_SERIAL_CORE_CONSOLE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1996
CONFIG_SOFT_FLOAT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4523
CONFIG_SYN_COOKIES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:90
CONFIG_SYSCTL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4002
CONFIG_SYSLOG_UNIXSOCK_SUPPORT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:99
CONFIG_SYSVIPC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4166
CONFIG_RG_PING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:316
CONFIG_RG_TRACEROUTE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:317
CONFIG_RG_TCP_DETECT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:318
CONFIG_RG_ARP_PING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:381
CONFIG_RG_TODC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:452
CONFIG_RG_SNTPS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4511
export CONFIG_ULIBC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:867
CONFIG_ULIBC_DO_C99_MATH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3369
export CONFIG_RG_CXX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4514
CONFIG_UNIX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1002
CONFIG_USB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3984
CONFIG_USB_STORAGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2232
export TARGET_ENDIANESS=BIG
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:862
BOARD=VRX268
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:863
FIRM=Lantiq
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4521
CONFIG_RG_FACTORY_SETTINGS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4131
CONFIG_RG_HW_BUTTONS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:875
export CONFIG_RG_CONSOLE_DEVICE=ttyS0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:576
CONFIG_RG_SAMBA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:190
CONFIG_RG_QUAGGA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4527
OPENRG_CHRDEV_MAJOR=240
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4526
OPENRG_CHRDEV_NAME=rg_chrdev
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1006
CONFIG_RG_ATHEROS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:885
CONFIG_RG_ATHEROS_HW_AR5416=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:886
CONFIG_HW_80211AC_ATHEROS_QCA98XX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1007
CONFIG_ATHEROS_AR5008_PCI_SWAP=1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:887
CONFIG_RG_ATHEROS_FUSION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1017
CONFIG_BUILD_ADF_NET=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1025
CONFIG_FUSION_DFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:888
CONFIG_FUSION_PKT_LOG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3363
CONFIG_RG_WPS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3364
CONFIG_RG_WSC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4209
CONFIG_RG_HOSTAPD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4211
CONFIG_HOSTAPD_RSN_PREAUTH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4210
CONFIG_HOSTAPD_DRIVER_MADWIFI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3610
CONFIG_GCC_CAN_INLINE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:574
CONFIG_RG_DISK_MNG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:617
CONFIG_RG_DISKTYPE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:575
export CONFIG_RG_FILESERVER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3776
CONFIG_RG_LARGE_FILE_SUPPORT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:624
CONFIG_RG_CODEPAGE="437"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:621
CONFIG_MSDOS_PARTITION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:626
CONFIG_FAT_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:622
CONFIG_FAT_DEFAULT_CODEPAGE=437
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:636
CONFIG_FAT_DEFAULT_IOCHARSET="iso8859-1"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:627
CONFIG_MSDOS_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:628
CONFIG_VFAT_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4118
CONFIG_NLS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4124
CONFIG_NLS_DEFAULT="iso8859-1"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4119
CONFIG_NLS_CODEPAGE_437=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4120
CONFIG_NLS_CODEPAGE_850=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4121
CONFIG_NLS_UTF8=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4122
CONFIG_NLS_ISO8859_1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:578
CONFIG_RG_FILESERVER_ACLS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:587
CONFIG_FS_POSIX_ACL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:595
CONFIG_EXT3_FS_POSIX_ACL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:590
CONFIG_EXT2_FS_POSIX_ACL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:596
CONFIG_EXT3_FS_XATTR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:597
CONFIG_EXT3_FS_XATTR_SHARING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:591
CONFIG_EXT2_FS_XATTR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:592
CONFIG_EXT2_FS_XATTR_SHARING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:600
CONFIG_FS_MBCACHE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:447
CONFIG_RG_SSH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:448
CONFIG_RG_SFTP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:573
CONFIG_RG_RAID=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:648
CONFIG_MD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:649
export CONFIG_BLK_DEV_MD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:650
CONFIG_MD_RAID0=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:651
CONFIG_MD_RAID1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:652
CONFIG_MD_RAID5=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4077
CONFIG_SCSI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4078
export CONFIG_BLK_DEV_SD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4079
CONFIG_SD_EXTRA_DEVS=32
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:537
CONFIG_VLAN_8021Q=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:534
CONFIG_RG_VLAN_8021Q=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:55
CONFIG_RG_OS_LINUX_26=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:111
CONFIG_RG_LANGUAGES=DEF
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4182
CONFIG_RG_DIST_LANG=eng
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2239
CONFIG_BOOT_ELF32=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2225
CONFIG_MIPS_L1_CACHE_SHIFT=5
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1807
CONFIG_CPU_HAS_PREFETCH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1806
CONFIG_CPU_HAS_LLSC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1811
CONFIG_CPU_HAS_SYNC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2223
CONFIG_DMA_NONCOHERENT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1805
CONFIG_CPU_MIPSR2=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1808
CONFIG_CPU_MIPSR2_IRQ_VI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1809
CONFIG_CPU_MIPSR2_IRQ_EI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1810
CONFIG_CPU_MIPSR2_SRS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1815
CONFIG_DMA_NEED_PCI_MAP_STATE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1820
CONFIG_MIPS_MT_DISABLED=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1821
CONFIG_MIPS_MT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1823
CONFIG_MTSCHED=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1824
CONFIG_MIPS_VPE_LOADER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1825
CONFIG_MIPS_VPE_LOADER_TOM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1838
CONFIG_32BIT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2226
CONFIG_PAGE_SIZE_4KB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1880
CONFIG_GENERIC_IRQ_PROBE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1884
CONFIG_FLATMEM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1885
CONFIG_FLAT_NODE_MEM_MAP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:2462
CRAMFS_SIZE_WIDTH=24
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:941
CONFIG_ECRYPT_FS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4452
CONFIG_ZLIB_INFLATE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4453
CONFIG_ZLIB_DEFLATE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4444
CONFIG_LZO_COMPRESS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4445
CONFIG_LZO_DECOMPRESS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:952
CONFIG_RG_PPP_ALLOW_EMPTY_PASSWORD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:510
CONFIG_RG_OAM_PING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4196
CONFIG_RG_FRAG_CACHE=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3663
CONFIG_RG_XML=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:343
CONFIG_ZC_IP_AUTO_DETECTION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:358
CONFIG_RG_LANG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4341
CONFIG_RG_ZLIB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4342
CONFIG_RG_KERNEL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4343
CONFIG_RG_MAIN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4344
CONFIG_RG_VENDOR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:112
LOCAL_COUNTRY_CODE="44"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4438
export CONFIG_RG_THREADS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:304
CONFIG_RG_OSS_RMT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:303
CONFIG_RG_RMT_MNG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:439
CONFIG_RG_EVENT_LOGGING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:577
CONFIG_RG_WINS_SERVER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:572
CONFIG_RG_FS_BACKUP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:872
CONFIG_TOS_DSCP_RFC2474=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:244
CONFIG_RG_IPROUTE2=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:705
CONFIG_RG_QOS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:920
CONFIG_RG_QOS_INGRESS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:909
CONFIG_RG_8021P_QOS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:910
CONFIG_RG_STRONG_HOST_MODEL=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:708
CONFIG_RG_QOS_PRIO_BANDS=3
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:925
CONFIG_RG_VLAN_DSCP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:876
CONFIG_NET_SCHED=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:882
CONFIG_NET_SCH_INGRESS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:879
CONFIG_NET_SCH_HTB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:880
CONFIG_NET_SCH_WRR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:914
CONFIG_NET_SCH_ATM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:884
CONFIG_NET_SCH_PRIO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:886
CONFIG_NET_SCH_RED=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:888
CONFIG_NET_SCH_SFQ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:890
CONFIG_NET_SCH_DSMARK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:892
CONFIG_NET_SCH_FIFO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:894
CONFIG_NET_QOS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:896
CONFIG_NET_ESTIMATOR=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:898
CONFIG_NET_CLS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:900
CONFIG_NET_CLS_POLICE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:902
CONFIG_NET_CLS_TCINDEX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:904
CONFIG_NET_CLS_FW=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:906
CONFIG_NET_CLS_U32=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:908
CONFIG_NET_CLS_RSVP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:910
CONFIG_NET_CLS_RSVP6=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:848
CONFIG_IP_ROUTE_MULTIPATH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:850
CONFIG_IP_ROUTE_VERBOSE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:917
CONFIG_IP_ROUTE_FWMARK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:852
CONFIG_IP_MULTIPLE_TABLES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:855
CONFIG_IP_ROUTE_TOS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:185
CONFIG_RG_TUNNELS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:249
CONFIG_RG_FOUNDATION_CORE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:182
CONFIG_RG_TARGET_LINUX=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:125
CONFIG_RG_HOST_LINUX=y
# Set by command line:
CONFIG_RG_GPL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:825
MODULE_RG_FOUNDATION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:833
MODULE_RG_ADVANCED_MANAGEMENT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:826
MODULE_RG_DSL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:847
MODULE_RG_PPP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:839
MODULE_RG_VLAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:843
MODULE_RG_UPNP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:834
MODULE_RG_ADVANCED_ROUTING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:831
MODULE_RG_FIREWALL_AND_SECURITY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:846
MODULE_RG_IPSEC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:827
MODULE_RG_FILESERVER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:835
MODULE_RG_WLAN_AND_ADVANCED_WLAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:912
MODULE_RG_URL_FILTERING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:838
MODULE_RG_QOS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:841
MODULE_RG_DSLHOME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:842
MODULE_RG_TR_064=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:911
MODULE_RG_REDUCE_SUPPORT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:865
MODULE_RG_PSE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:844
MODULE_RG_WPS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:853
CONFIG_HW_ETH_WAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:855
CONFIG_HW_VDSL_WAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:854
CONFIG_HW_DSL_WAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:852
CONFIG_HW_ETH_LAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:862
CONFIG_HW_USB_STORAGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:879
CONFIG_HW_LEDS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:880
CONFIG_HW_BUTTONS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:840
CONFIG_HW_ENCRYPTION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:938
CONFIG_HW_SWITCH_FIRST_PHY=0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:879
CONFIG_HW_FLASH_NAND=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:410
CONFIG_RG_MAC_CLONING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:901
CONFIG_RG_ENERGY_SAVING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:893
CONFIG_RG_POWER_MANAGEMENT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:348
CONFIG_RG_UNCONFIGURED_WAN_INTERCEPTION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:251
CONFIG_RG_CHECK_BAD_REBOOTS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:817
export CONFIG_RG_INITFS_RAMFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3777
CONFIG_RG_MAINFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:818
export CONFIG_RG_MAINFS_CRAMFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3792
export CONFIG_RG_MODFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:819
export CONFIG_RG_MODFS_CRAMFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:820
export CONFIG_RG_CRAMFS_COMP_METHOD=lzma
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:146
CONFIG_RG_KERNEL_COMP_METHOD=lzma
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3913
CONFIG_RG_LZMA_COMPRESSED_KERNEL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:236
CONFIG_RG_LICENSE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2123
LANG_COMPILER_OPT=--select "DEF"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2111
LANG_COMPILER=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/util/lang_compiler
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:149
ENDIAN_LDFLAGS=-EB
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:158
ENDIAN_CFLAGS=-meb
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:137
OS_PATH=$(1)
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:192
TOOLCHAIN_ROOT=/media/data/build/router
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:193
export I386_TARGET_MACHINE=i386-jungo-linux-gnu
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:195
export I386_TOOLS_PREFIX=/media/data/build/router/i386-jungo-linux-gnu
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:291
export TARGET_MACHINE=mips-openwrt-linux-musl
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:303
TARGET_PREFIX=mips-openwrt-linux-musl
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:397
export TOOLS_PREFIX=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:415
export CROSS_COMPILE=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:871
export LIBC_IN_TOOLCHAIN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:639
export CC=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/build/rg_gcc
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:662
export CXX=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-g++
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:718
export TARGET_CXX=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-g++
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:712
export TARGET_CC=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-gcc
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:715
export TARGET_CPP=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-gcc -E
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:720
REAL_GCC=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-gcc
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:697
export CC_FOR_BUILD=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-gcc -DCC_FOR_BUILD -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/include -DCONFIG_HAS_MMU
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:701
export CXX_FOR_BUILD=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-g++ -DCC_FOR_BUILD -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/include -DCONFIG_HAS_MMU
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1328
GCC_HAS_SIZE_OPTIMIZE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:743
GCC_VERSION=4.8.3
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:805
export AR=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-ar
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:806
export LD=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-ld
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:807
export AS=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-as
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:808
export NM=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-nm
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:809
export RANLIB=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-ranlib
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:810
export STRIP=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-strip
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:811
export SIZE=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-size
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:812
export OBJCOPY=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-objcopy
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:813
export OBJDUMP=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-musl-objdump
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:779
HOST_AR=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-ar
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:780
HOST_LD=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-ld
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:781
HOST_AS=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-as
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:782
HOST_NM=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-nm
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:783
HOST_RANLIB=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-ranlib
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:784
HOST_STRIP=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-strip
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:785
HOST_SIZE=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-size
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:786
HOST_OBJCOPY=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-objcopy
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:787
HOST_OBJDUMP=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-objdump
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:940
YACC=bison
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:972
LEX=/usr/bin/flex
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:941
YFLAGS=-y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:988
SPCC=echo
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:986
RG_INCLUDE_DIR=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/include
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:983
export RG_BIN=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/build/bin/
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:985
export RG_LIB=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/build/lib/
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:984
export RG_BUILD=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/build/
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1000
export NET_TOOLS_MAKE_FILE=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/include/net-tools-config.make
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1088
LOCAL_ADD_RG_KERNEL_FOR_TARGET=-idirafter /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/include
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2344
export PATH=.:.:.:.:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin:/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin:/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin:/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1002
DYNAMIC_LINKER=/lib/ld-linux.so.1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1098
PERM_STORAGE_FILES_DIR=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/flash/
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1003
LZMAMK=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/lzma/SRC/lzma.mak
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1096
BINFRMT_FILE=target_binfmt_elf.mak
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1065
export COMPRESSED_RAMDISK=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/arch/mips/ramdisk/ramdisk.gz
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1075
export MODFS_DISK=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/usr/modfs.img
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:996
AUTOCONF_H=include/linux/autoconf.h
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:818
PROD_LINUX_TARGET=bzImage.initrd
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:821
export OS_TARGET=bzImage.initrd
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:989
HOSTCC=gcc -DCONFIG_HAS_MMU
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:990
HOSTCPP=gcc -DCONFIG_HAS_MMU -E
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:656
CPP=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/build/rg_gcc -E
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:991
CPP_FOR_BUILD=/media/data/build/router/i386-jungo-linux-gnu/bin/i386-jungo-linux-gnu-gcc -DCC_FOR_BUILD -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/include -DCONFIG_HAS_MMU -E
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1401
RG_CFLAGS=-D_LIBC_REENTRANT -Wall -g -Os 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1047
STATIC_MOD_DIR=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/kernel/modules_static/
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1049
export RG_LIBPTHREAD_VERSION=0.8
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1050
export NEEDED_SYMBOLS=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/needed_symbols.lst
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1314
export COMPRESSED_DISK=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/usr/mainfs.img
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1304
export BOOTLDR_COMPRESSED_DISK=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/arch/mips/boot/bootldr_ramdisk.gz
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:993
export GENROMFS=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/genromfs/genromfs
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1154
export PROD_KERNEL_IMAGE=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/vmlinux
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1119
OPENRG_IMG=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/openrg.img
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1124
OPENRG_RMT_UPDATE_IMG=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/openrg.rmt
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1125
OPENRG_RMT_UPDATE_RSA_IMG=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/openrg.rms
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1127
OPENRG_RMT_UPDATE_RSA_ENC_IMG=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/openrg_enc.rms
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1139
OPENRG_PROD=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/openrg.prod
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1141
FLASH_IMG=BUILDDIR/flash.img
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1140
BOOTLDR_IMG=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/bootldr/arch/boot.img
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1244
HAVE_GC_SECTIONS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1360
HAVE_ATTRIBUTE_NONNULL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1295
LINUX_ARCH_PATH=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux/arch/mips
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1548
ARCH_CFLAGS=-meb -msoft-float -march=mips32r2 -fno-builtin -mabi=32 -Wa,-mips32r2 -Wno-pointer-sign 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1227
FLASH_IMG_OFFSET=0x0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1228
FLASH_IMG_REAL_OFFSET=0x0
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1836
RG_LINUX_CFLAGS=-Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -g -fomit-frame-pointer -Os -G 0 -mno-abicalls -fno-pic -mlong-calls -ffreestanding -meb -msoft-float -march=mips32r2 -fno-builtin -mabi=32 -Wa,-mips32r2 -Wno-pointer-sign  -msoft-float -Wa,--trap -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include/asm/ifx -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include2/asm/mach-generic  -D__KERNEL__ -D__TARGET__  -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include2 -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/os/linux-2.6/include2 -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/os/linux-2.6/include -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/arch/mips -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/arch/mips/include -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/os/linux-2.6/arch/mips 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1833
RG_LINUX_26_CFLAGS=-I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include2 -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/os/linux-2.6/include2 -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/os/linux-2.6/include -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/arch/mips -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/arch/mips/include -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/os/linux-2.6/arch/mips 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1854
LINUX_CFLAGS=-meb -include linux/autoconf.h
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1613
ARCH_LINUX_FLAGS=-meb -msoft-float -march=mips32r2 -fno-builtin -mabi=32 -Wa,-mips32r2 -Wno-pointer-sign  -msoft-float -Wa,--trap -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include/asm/ifx -I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/os/linux-2.6/include2/asm/mach-generic 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1924
LDFLAGS_ENVIR=-meb -L/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/lib 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1885
LOCAL_LDFLAGS=-L/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/lib -Wl,--dynamic-linker,/media/data/build/router/i386-jungo-linux-gnu/i386-jungo-linux-gnu/lib/ld-2.3.2.so -Wl,-rpath,/media/data/build/router/i386-jungo-linux-gnu/i386-jungo-linux-gnu/lib --static 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1943
LOCAL_CFLAGS=-I/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/include -D__HOST__ -O0 -Wall -Wstrict-prototypes --no-strict-aliasing -g
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:755
LIB_GCC_DIR_PREFIX=/media/data/build/router/toolchain-mips_34kc+dsp_gcc-4.8-linaro_musl-1.1.11/bin/../lib/gcc/mips-openwrt-linux-musl/4.8.3
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1970
CFLAGS_ENVIR=-Wstrict-prototypes --no-strict-aliasing -D_LIBC_REENTRANT -Wall -g -Os  -meb -msoft-float -march=mips32r2 -fno-builtin -mabi=32 -Wa,-mips32r2 -Wno-pointer-sign  -D__TARGET__ 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1979
OPENRG_LIB=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/util/libopenrg.so
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1982
OPENRG_GPL_LIB=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/util/libopenrg_gpl.so 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1988
OPENRG_GPL_LDLIBS=-lopenrg_gpl  
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2003
OPENRG_LDLIBS=-lopenrg -ljutil -lz -lssl -lcrypto -ldl -lopenrg -ljutil -lrg_config
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2041
OPENRG_LOCAL_LDLIBS=-llocal_openrg -llocal_jutil -llocal_rg_config -llocal_z -llocal_ssl -llocal_crypto 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2005
MGT_LDLIBS=-lmgt 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:2042
MGT_LOCAL_LDLIBS=-llocal_mgt 
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1006
UNITTEST_SPAWNER=/media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/build.SAGEM_HH5/pkg/util/jspawn -s 20
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_host.c:1039
CONFIG_ICONV_CONST_CAST=
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3668
CONFIG_RG_SESSION_MEMORY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1886
CONFIG_SPLIT_PTLOCK_CPUS=4
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:632
CONFIG_SWAP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:101
CONFIG_SLAB=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:1024
CONFIG_FW_LOADER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:974
CONFIG_IFX_ATM_OAM=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1832
CONFIG_SERIAL_IFX_ASC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1833
CONFIG_SERIAL_IFX_ASC_CONSOLE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1834
CONFIG_IFX_ASC_DEFAULT_BAUDRATE=115200
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1835
CONFIG_IFX_ASC_CONSOLE_ASC1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:950
CONFIG_RG_LIBC_CUSTOM_STREAMS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:824
CONFIG_RG_SOFTPATH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:867
CONFIG_HW_PSE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:826
CONFIG_RG_SOFTPATH_BY_HOOKS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:867
CONFIG_RG_HW_SAGEM_HH5_VRX268=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1800
CONFIG_LANTIQ_XWAY=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1826
CONFIG_IFX_VPE_EXT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1827
CONFIG_SOFT_WATCHDOG_VPE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1841
CONFIG_IFX_DMA_DESCRIPTOR_NUMBER=256
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1846
CONFIG_IFX_PMCU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1847
CONFIG_IFX_CPUFREQ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1855
CONFIG_IFX_DCDC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1844
CONFIG_IFX_CLOCK_CHANGE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1859
CONFIG_IFX_GPIO=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1857
CONFIG_DSL_MEI_CPE_DRV=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1860
CONFIG_IFX_PMU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1861
CONFIG_IFX_RCU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1874
CONFIG_IFX_WDT=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1928
CONFIG_MTD_IFX_NAND=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1929
CONFIG_MTD_IFX_NAND_LATCH_ENABLE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:908
CONFIG_IFX_ETH_FRAMEWORK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:907
CONFIG_GPHY_DRIVER=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:906
CONFIG_GE_MODE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:951
CONFIG_LANTIQ_VR9_PORT_SEP=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:961
CONFIG_LANTIQ_VR9_PORT_WAN_ETH=5
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:956
CONFIG_LANTIQ_VR9_VLAN_CPU=4001
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:962
CONFIG_LANTIQ_VR9_VLAN_WAN_ETH=4002
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:968
CONFIG_LANTIQ_VR9_VLAN_WAN_DSL=4003
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:883
CONFIG_IFX_PPA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:913
CONFIG_IFX_PPA_A5=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:914
CONFIG_IFX_PPA_E5=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:916
CONFIG_IFX_PPA_DATAPATH=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:917
CONFIG_IFX_PPA_API_PROC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1991
CONFIG_IFX_PPA_API_DIRECTPATH=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1992
CONFIG_IFX_PPA_API_DIRECTPATH_BRIDGING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1864
CONFIG_IFX_ETHSW_API=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1865
CONFIG_IFX_ETHSW_API_COC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1866
CONFIG_IFX_ETHSW_API_COC_PMCU=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1993
CONFIG_PTM_VECTORING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1837
CONFIG_LTQ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1845
CONFIG_LTQ_ADDON=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:905
CONFIG_RG_PTM_VLAN=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1954
CONFIG_USB_HOST_IFX=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1959
CONFIG_USB_HOST_IFX_1=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1963
CONFIG_USB_HOST_IFX_UNALIGNED_ADJ=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1964
CONFIG_USB_HOST_IFX_COC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1987
CONFIG_IFX_DSL_API=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:946
CONFIG_IFX_OS=m
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:865
CONFIG_VR9=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/hw_config.c:866
CONFIG_VR9_REF_BOARD=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:109
CONFIG_SHC_BT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:899
CONFIG_BT_QOS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:915
CONFIG_BT_OPENWIFI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:949
CONFIG_RG_BT_CERTIFICATES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:924
CONFIG_BT_SSIWI=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:114
CONFIG_RG_SIN227=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:115
CONFIG_RG_SIN351=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:877
CONFIG_RG_PERM_STORAGE_NAND=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:849
CONFIG_SHC_BT_DESIGN_DOC=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:923
CONFIG_BT_REMOTE_ASSISTANCE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:897
CONFIG_RG_ERROR_TIME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:898
CONFIG_PRINTK_TIME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:902
CONFIG_BT_MC_RETRANSMISSION=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:917
CONFIG_BT_SAAF=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:900
CONFIG_BT_AUTOSENSING=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:907
CONFIG_BT_EACS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:991
CONFIG_BT_BRIDGED_MODE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:903
CONFIG_BT_OIE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:981
CONFIG_BT_CONF_IN_FFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4386
CONFIG_TRACE_IRQFLAGS_SUPPORT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4387
CONFIG_ZONE_DMA=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:102
CONFIG_ZONE_DMA_FLAG=1
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:103
CONFIG_BLOCK=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:139
CONFIG_DEFAULT_TCP_CONG="cubic"
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4388
CONFIG_GENERIC_TIME=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4389
CONFIG_GENERIC_FIND_NEXT_BIT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:4390
CONFIG_GENERIC_HWEIGHT=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:853
CONFIG_FIB_RULES=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3544
CONFIG_BITREVERSE=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/config_target_os.c:91
CONFIG_PROC_SYSCTL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1828
CONFIG_WATCHDOG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:355
CONFIG_RG_RAND_POOL_RAM_INIT=y
# config_opt.c (default):
CONFIG_RG_RAND_POOL_RAM_INIT_SIZE=8388608
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:974
export CONFIG_RG_FFS=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:3699
export CONFIG_RG_FFS_MNT_DIR=/mnt/ffs
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/dist_config.c:993
CONFIG_RG_HW_WATCHDOG=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1875
CONFIG_RG_HW_WATCHDOG_IOCTL=y
# /media/data/build/router/bt_hh5a_rg-4.7.5.1/rg/pkg/build/feature_config.c:1876
export CONFIG_RG_HW_WATCHDOG_ARCH_LINUX_GENERIC=y
