/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009-2016
 * All rights reserved.
 *
 * $Revision: 96128 $
 * $Date: 2019-04-02 11:25:30 +0800 (Tue, 02 Apr 2019) $
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/longan/rtk_longan_table_struct.h>

#if defined(CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_UNTAG_FIELDS[] =
{
    {   /* name     LONGAN_UNTAG_PMSKtf */
        /* lsp */   3,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_VLAN_FIELDS[] =
{
    {   /* name     LONGAN_VLAN_MBRtf */
        /* lsp */   35,
        /* len */   29,
    },
    {   /* name     LONGAN_VLAN_MSTItf */
        /* lsp */   29,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_L2_HKEY_UCASTtf */
        /* lsp */   28,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_L2_HKEY_MCASTtf */
        /* lsp */   27,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_VLAN_PROFILEtf */
        /* lsp */   24,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_GROUP_MASKtf */
        /* lsp */   16,
        /* len */   8,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ */
#if defined(CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_VLAN_EGR_CNVT_FIELDS[] =
{
    {   /* name     LONGAN_VLAN_EGR_CNVT_VALIDtf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_PORT_TYPEtf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_PORT_IDtf */
        /* lsp */   184,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_OTAG_IFtf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_OPRItf */
        /* lsp */   180,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_OVIDtf */
        /* lsp */   168,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_ITAG_IFtf */
        /* lsp */   167,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_IPRItf */
        /* lsp */   164,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_IVIDtf */
        /* lsp */   152,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_INT_VID_RNG_CHKtf */
        /* lsp */   120,
        /* len */   32,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_PORT_TYPEtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_PORT_IDtf */
        /* lsp */   113,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_OTAG_IFtf */
        /* lsp */   112,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_OPRItf */
        /* lsp */   109,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_OVIDtf */
        /* lsp */   97,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_ITAG_IFtf */
        /* lsp */   96,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_IPRItf */
        /* lsp */   93,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_IVIDtf */
        /* lsp */   81,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_BMSK_INT_VID_RNG_CHKtf */
        /* lsp */   49,
        /* len */   32,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OTPID_ASSIGNtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OTPID_IDXtf */
        /* lsp */   46,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OTAG_STS_ASSIGNtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OTAG_STStf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OPRI_ASSIGNtf */
        /* lsp */   43,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OPRItf */
        /* lsp */   40,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OVID_ASSIGNtf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_OVIDtf */
        /* lsp */   26,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_ITPID_ASSIGNtf */
        /* lsp */   25,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_ITPID_IDXtf */
        /* lsp */   23,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_ITAG_STS_ASSIGNtf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_ITAG_STStf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_IPRI_ASSIGNtf */
        /* lsp */   19,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_IPRItf */
        /* lsp */   16,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_IVID_ASSIGNtf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_EGR_CNVT_IVIDtf */
        /* lsp */   2,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_VLAN_IGR_CNVT_FIELDS[] =
{
    {   /* name     LONGAN_VLAN_IGR_CNVT_VALIDtf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_PORT_TYPEtf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_PORT_IDtf */
        /* lsp */   184,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_OTAG_IFtf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_OPRItf */
        /* lsp */   180,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_OVIDtf */
        /* lsp */   168,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_ITAG_IFtf */
        /* lsp */   167,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_IPRItf */
        /* lsp */   164,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_IVIDtf */
        /* lsp */   152,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ORI_VID_RNG_CHKtf */
        /* lsp */   120,
        /* len */   32,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_PORT_TYPEtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_PORT_IDtf */
        /* lsp */   113,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_OTAG_IFtf */
        /* lsp */   112,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_OPRItf */
        /* lsp */   109,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_OVIDtf */
        /* lsp */   97,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_ITAG_IFtf */
        /* lsp */   96,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_IPRItf */
        /* lsp */   93,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_IVIDtf */
        /* lsp */   81,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_BMSK_ORI_VID_RNG_CHKtf */
        /* lsp */   49,
        /* len */   32,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OTPID_ASSIGNtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OTPID_IDXtf */
        /* lsp */   46,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OTAG_STS_ASSIGNtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OTAG_STStf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OPRI_ASSIGNtf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OPRItf */
        /* lsp */   39,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OVID_ASSIGNtf */
        /* lsp */   37,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_OVIDtf */
        /* lsp */   25,
        /* len */   12,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ITPID_ASSIGNtf */
        /* lsp */   24,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ITPID_IDXtf */
        /* lsp */   22,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ITAG_STS_ASSIGNtf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_ITAG_STStf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_IPRI_ASSIGNtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_IPRItf */
        /* lsp */   16,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_IVID_ASSIGNtf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_IGR_CNVT_IVIDtf */
        /* lsp */   2,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_VLAN_IP_BASED_FIELDS[] =
{
    {   /* name     LONGAN_VLAN_IP_BASED_VALIDtf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_PORT_TYPEtf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_PORT_IDtf */
        /* lsp */   184,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_OVID_VALIDtf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_IVID_VALIDtf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_SIPtf */
        /* lsp */   150,
        /* len */   32,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_BMSK_PORT_TYPEtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_BMSK_PORT_IDtf */
        /* lsp */   113,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_BMSK_OVID_VALIDtf */
        /* lsp */   112,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_BMSK_IVID_VALIDtf */
        /* lsp */   111,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_BMSK_SIPtf */
        /* lsp */   79,
        /* len */   32,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_FWD_ACTtf */
        /* lsp */   46,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_IGNORE_IGR_FLTRtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_VLAN_TYPEtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_TPID_ASSIGNtf */
        /* lsp */   43,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_TPID_IDXtf */
        /* lsp */   41,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_TAG_STS_ASSIGNtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_TAG_STStf */
        /* lsp */   39,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_PRI_ASSIGNtf */
        /* lsp */   38,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_PRItf */
        /* lsp */   35,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_VID_ASSIGNtf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_IP_BASED_VIDtf */
        /* lsp */   22,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_VLAN_MAC_BASED_FIELDS[] =
{
    {   /* name     LONGAN_VLAN_MAC_BASED_VALIDtf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_PORT_TYPEtf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_PORT_IDtf */
        /* lsp */   184,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_OVID_VALIDtf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_IVID_VALIDtf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_SMACtf */
        /* lsp */   134,
        /* len */   48,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_BMSK_PORT_TYPEtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_BMSK_PORT_IDtf */
        /* lsp */   113,
        /* len */   6,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_BMSK_OVID_VALIDtf */
        /* lsp */   112,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_BMSK_IVID_VALIDtf */
        /* lsp */   111,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_BMSK_SMACtf */
        /* lsp */   63,
        /* len */   48,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_FWD_ACTtf */
        /* lsp */   46,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_IGNORE_IGR_FLTRtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_VLAN_TYPEtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_TPID_ASSIGNtf */
        /* lsp */   43,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_TPID_IDXtf */
        /* lsp */   41,
        /* len */   2,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_TAG_STS_ASSIGNtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_TAG_STStf */
        /* lsp */   39,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_PRI_ASSIGNtf */
        /* lsp */   38,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_PRItf */
        /* lsp */   35,
        /* len */   3,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_VID_ASSIGNtf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     LONGAN_VLAN_MAC_BASED_VIDtf */
        /* lsp */   22,
        /* len */   12,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_LAG_FIELDS[] =
{
    {   /* name     LONGAN_LAG_NUM_TX_CANDItf */
        /* lsp */   89,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_L2_HASH_MSK_IDXtf */
        /* lsp */   88,
        /* len */   1,
    },
    {   /* name     LONGAN_LAG_IP4_HASH_MSK_IDXtf */
        /* lsp */   87,
        /* len */   1,
    },
    {   /* name     LONGAN_LAG_IP6_HASH_MSK_IDXtf */
        /* lsp */   86,
        /* len */   1,
    },
    {   /* name     LONGAN_LAG_SEP_DLF_BCAST_ENtf */
        /* lsp */   85,
        /* len */   1,
    },
    {   /* name     LONGAN_LAG_SEP_KWN_MC_ENtf */
        /* lsp */   84,
        /* len */   1,
    },
    {   /* name     LONGAN_LAG_TRK_DEV7tf */
        /* lsp */   80,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT7tf */
        /* lsp */   74,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV6tf */
        /* lsp */   70,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT6tf */
        /* lsp */   64,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV5tf */
        /* lsp */   58,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT5tf */
        /* lsp */   52,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV4tf */
        /* lsp */   48,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT4tf */
        /* lsp */   42,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV3tf */
        /* lsp */   38,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT3tf */
        /* lsp */   32,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV2tf */
        /* lsp */   26,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT2tf */
        /* lsp */   20,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV1tf */
        /* lsp */   16,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT1tf */
        /* lsp */   10,
        /* len */   6,
    },
    {   /* name     LONGAN_LAG_TRK_DEV0tf */
        /* lsp */   6,
        /* len */   4,
    },
    {   /* name     LONGAN_LAG_TRK_PORT0tf */
        /* lsp */   0,
        /* len */   6,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_SRC_TRK_MAP_FIELDS[] =
{
    {   /* name     LONGAN_SRC_TRK_MAP_TRK_VALIDtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     LONGAN_SRC_TRK_MAP_TRK_IDtf */
        /* lsp */   25,
        /* len */   6,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_MSTI_FIELDS[] =
{
    {   /* name     LONGAN_MSTI_STATE_PORT28tf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT27tf */
        /* lsp */   60,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT26tf */
        /* lsp */   58,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT25tf */
        /* lsp */   56,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT24tf */
        /* lsp */   54,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT23tf */
        /* lsp */   52,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT22tf */
        /* lsp */   50,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT21tf */
        /* lsp */   48,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT20tf */
        /* lsp */   46,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT19tf */
        /* lsp */   44,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT18tf */
        /* lsp */   42,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT17tf */
        /* lsp */   40,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT16tf */
        /* lsp */   38,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT15tf */
        /* lsp */   36,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT14tf */
        /* lsp */   34,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT13tf */
        /* lsp */   32,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT12tf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT11tf */
        /* lsp */   28,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT10tf */
        /* lsp */   26,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT9tf */
        /* lsp */   24,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT8tf */
        /* lsp */   22,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT7tf */
        /* lsp */   20,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT6tf */
        /* lsp */   18,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT5tf */
        /* lsp */   16,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT4tf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT3tf */
        /* lsp */   12,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT2tf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT1tf */
        /* lsp */   8,
        /* len */   2,
    },
    {   /* name     LONGAN_MSTI_STATE_PORT0tf */
        /* lsp */   6,
        /* len */   2,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_PORT_ISO_CTRL_FIELDS[] =
{
    {   /* name     LONGAN_PORT_ISO_CTRL_P_ISO_MBR_0tf */
        /* lsp */   3,
        /* len */   29,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L2_CAM_MC_FIELDS[] =
{
    {   /* name     LONGAN_L2_CAM_MC_MACtf */
        /* lsp */   48,
        /* len */   48,
    },
    {   /* name     LONGAN_L2_CAM_MC_FID_RVIDtf */
        /* lsp */   32,
        /* len */   12,
    },
    {   /* name     LONGAN_L2_CAM_MC_VALIDtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_MC_MC_PMSK_IDXtf */
        /* lsp */   16,
        /* len */   10,
    },
    {   /* name     LONGAN_L2_CAM_MC_NEXT_HOPtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_MC_MAC_IDXtf */
        /* lsp */   0,
        /* len */   11,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L2_CAM_UC_FIELDS[] =
{
    {   /* name     LONGAN_L2_CAM_UC_MACtf */
        /* lsp */   48,
        /* len */   48,
    },
    {   /* name     LONGAN_L2_CAM_UC_FID_RVIDtf */
        /* lsp */   32,
        /* len */   12,
    },
    {   /* name     LONGAN_L2_CAM_UC_VALIDtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_IS_TRKtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_SPAtf */
        /* lsp */   20,
        /* len */   10,
    },
    {   /* name     LONGAN_L2_CAM_UC_AGEtf */
        /* lsp */   17,
        /* len */   3,
    },
    {   /* name     LONGAN_L2_CAM_UC_SA_BLKtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_DA_BLKtf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_STATICtf */
        /* lsp */   14,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_SUSPENDtf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_NEXT_HOPtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_CAM_UC_VIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L2_MC_FIELDS[] =
{
    {   /* name     LONGAN_L2_MC_MACtf */
        /* lsp */   48,
        /* len */   48,
    },
    {   /* name     LONGAN_L2_MC_FID_RVIDtf */
        /* lsp */   32,
        /* len */   12,
    },
    {   /* name     LONGAN_L2_MC_VALIDtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_MC_MC_PMSK_IDXtf */
        /* lsp */   16,
        /* len */   10,
    },
    {   /* name     LONGAN_L2_MC_NEXT_HOPtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_MC_MAC_IDXtf */
        /* lsp */   0,
        /* len */   11,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L2_UC_FIELDS[] =
{
    {   /* name     LONGAN_L2_UC_MACtf */
        /* lsp */   48,
        /* len */   48,
    },
    {   /* name     LONGAN_L2_UC_FID_RVIDtf */
        /* lsp */   32,
        /* len */   12,
    },
    {   /* name     LONGAN_L2_UC_VALIDtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_IS_TRKtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_SPAtf */
        /* lsp */   20,
        /* len */   10,
    },
    {   /* name     LONGAN_L2_UC_AGEtf */
        /* lsp */   17,
        /* len */   3,
    },
    {   /* name     LONGAN_L2_UC_SA_BLKtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_DA_BLKtf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_STATICtf */
        /* lsp */   14,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_SUSPENDtf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_NEXT_HOPtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     LONGAN_L2_UC_VIDtf */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_MC_PORTMASK_FIELDS[] =
{
    {   /* name     LONGAN_MC_PORTMASK_PORTMASKtf */
        /* lsp */   3,
        /* len */   29,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_METER_MARKER)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_METER_FIELDS[] =
{
    {   /* name     LONGAN_METER_TYPEtf */
        /* lsp */   94,
        /* len */   2,
    },
    {   /* name     LONGAN_METER_MODEtf */
        /* lsp */   93,
        /* len */   1,
    },
    {   /* name     LONGAN_METER_COLOR_AWAREtf */
        /* lsp */   92,
        /* len */   1,
    },
    {   /* name     LONGAN_METER_LB0_RATEtf */
        /* lsp */   72,
        /* len */   20,
    },
    {   /* name     LONGAN_METER_LB1_RATEtf */
        /* lsp */   52,
        /* len */   20,
    },
    {   /* name     LONGAN_METER_LB0_BStf */
        /* lsp */   35,
        /* len */   17,
    },
    {   /* name     LONGAN_METER_LB1_BStf */
        /* lsp */   18,
        /* len */   17,
    },
    {   /* name     LONGAN_METER_RSTtf */
        /* lsp */   17,
        /* len */   1,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_METER_MARKER */
#if defined(CONFIG_SDK_CHIP_FEATURE_REMARKING)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_REMARK_FIELDS[] =
{
    {   /* name     LONGAN_REMARK_IPRI_DFLT_PRItf */
        /* lsp */   8,
        /* len */   3,
    },
    {   /* name     LONGAN_REMARK_OPRI_DFLT_PRItf */
        /* lsp */   4,
        /* len */   3,
    },
    {   /* name     LONGAN_REMARK_IPRI_DFLT_SRCtf */
        /* lsp */   2,
        /* len */   1,
    },
    {   /* name     LONGAN_REMARK_OPRI_DFLT_SRCtf */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_REMARKING */
#if defined(CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_EGR_INTF_FIELDS[] =
{
    {   /* name     LONGAN_L3_EGR_INTF_DST_VIDtf */
        /* lsp */   41,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_EGR_INTF_SMAC_IDXtf */
        /* lsp */   35,
        /* len */   6,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP_MTU_IDXtf */
        /* lsp */   32,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP6_MTU_IDXtf */
        /* lsp */   28,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IPMC_TTL_SCOPEtf */
        /* lsp */   20,
        /* len */   8,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP6MC_HL_SCOPEtf */
        /* lsp */   12,
        /* len */   8,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP_ICMP_REDIRECT_ACTtf */
        /* lsp */   9,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP6_ICMP_REDIRECT_ACTtf */
        /* lsp */   6,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP_PBR_ICMP_REDIRECT_ACTtf */
        /* lsp */   3,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_EGR_INTF_IP6_PBR_ICMP_REDIRECT_ACTtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_EGR_INTF_LIST_FIELDS[] =
{
    {   /* name     LONGAN_L3_EGR_INTF_LIST_OIL_NEXTtf */
        /* lsp */   21,
        /* len */   9,
    },
    {   /* name     LONGAN_L3_EGR_INTF_LIST_EOLtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_EGR_INTF_LIST_TTL_DECtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_EGR_INTF_LIST_TTL_CHKtf */
        /* lsp */   18,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_EGR_INTF_LIST_SA_REPLACEtf */
        /* lsp */   17,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_EGR_INTF_LIST_L3_EGR_INTF_BSSID_IDXtf */
        /* lsp */   10,
        /* len */   7,
    },
    {   /* name     LONGAN_L3_EGR_INTF_LIST_MC_PMSK_IDXtf */
        /* lsp */   0,
        /* len */   10,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_EGR_INTF_MAC_FIELDS[] =
{
    {   /* name     LONGAN_L3_EGR_INTF_MAC_MACtf */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_HOST_ROUTE_IP6MC_FIELDS[] =
{
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_VALIDtf */
        /* lsp */   351,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_ENTRY_TYPEtf */
        /* lsp */   349,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_IPMC_TYPEtf */
        /* lsp */   348,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_SIPtf */
        /* lsp */   192,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_GIPtf */
        /* lsp */   64,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_HITtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_TTL_MINtf */
        /* lsp */   53,
        /* len */   8,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_MTU_MAX_IDXtf */
        /* lsp */   50,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_STACK_FWD_PMSKtf */
        /* lsp */   46,
        /* len */   4,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_VID_CMPtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_VIDtf */
        /* lsp */   33,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_QOS_AStf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_QOS_PRItf */
        /* lsp */   29,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_L2_ENtf */
        /* lsp */   28,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_L2_ACTtf */
        /* lsp */   26,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_L2_MC_PMSK_IDXtf */
        /* lsp */   16,
        /* len */   10,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_L3_ENtf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_L3_ACTtf */
        /* lsp */   13,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_RPF_CHK_ENtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_RPF_FAIL_ACTtf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_OIL_IDX_VALIDtf */
        /* lsp */   9,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6MC_OIL_IDXtf */
        /* lsp */   0,
        /* len */   9,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_HOST_ROUTE_IP6UC_FIELDS[] =
{
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_VALIDtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_ENTRY_TYPEtf */
        /* lsp */   157,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_HITtf */
        /* lsp */   148,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_DST_NULL_INTFtf */
        /* lsp */   147,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_ACTIONtf */
        /* lsp */   145,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_NH_IDXtf */
        /* lsp */   134,
        /* len */   11,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_TTL_DECtf */
        /* lsp */   133,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_TTL_CHKtf */
        /* lsp */   132,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_QOS_AStf */
        /* lsp */   131,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_QOS_PRItf */
        /* lsp */   128,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IP6UC_IPtf */
        /* lsp */   0,
        /* len */   128,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_HOST_ROUTE_IPMC_FIELDS[] =
{
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_VALIDtf */
        /* lsp */   351,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_ENTRY_TYPEtf */
        /* lsp */   349,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_IPMC_TYPEtf */
        /* lsp */   348,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_SIPtf */
        /* lsp */   192,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_GIPtf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_HITtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_TTL_MINtf */
        /* lsp */   53,
        /* len */   8,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_MTU_MAX_IDXtf */
        /* lsp */   50,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_STACK_FWD_PMSKtf */
        /* lsp */   46,
        /* len */   4,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_VID_CMPtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_VIDtf */
        /* lsp */   33,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_QOS_AStf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_QOS_PRItf */
        /* lsp */   29,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_L2_ENtf */
        /* lsp */   28,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_L2_ACTtf */
        /* lsp */   26,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_L2_MC_PMSK_IDXtf */
        /* lsp */   16,
        /* len */   10,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_L3_ENtf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_L3_ACTtf */
        /* lsp */   13,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_RPF_CHK_ENtf */
        /* lsp */   12,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_RPF_FAIL_ACTtf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_OIL_IDX_VALIDtf */
        /* lsp */   9,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPMC_OIL_IDXtf */
        /* lsp */   0,
        /* len */   9,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_HOST_ROUTE_IPUC_FIELDS[] =
{
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_VALIDtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_ENTRY_TYPEtf */
        /* lsp */   157,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_HITtf */
        /* lsp */   148,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_DST_NULL_INTFtf */
        /* lsp */   147,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_ACTIONtf */
        /* lsp */   145,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_NH_IDXtf */
        /* lsp */   134,
        /* len */   11,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_TTL_DECtf */
        /* lsp */   133,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_TTL_CHKtf */
        /* lsp */   132,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_QOS_AStf */
        /* lsp */   131,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_QOS_PRItf */
        /* lsp */   128,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_HOST_ROUTE_IPUC_IPtf */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_NEXTHOP_FIELDS[] =
{
    {   /* name     LONGAN_L3_NEXTHOP_DMAC_IDXtf */
        /* lsp */   7,
        /* len */   15,
    },
    {   /* name     LONGAN_L3_NEXTHOP_L3_EGR_INTF_IDXtf */
        /* lsp */   0,
        /* len */   7,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_PREFIX_ROUTE_IP6MC_FIELDS[] =
{
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_VALIDtf */
        /* lsp */   639,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_ENTRY_TYPEtf */
        /* lsp */   637,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_IPMC_TYPEtf */
        /* lsp */   636,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_ROUNDtf */
        /* lsp */   635,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_VIDtf */
        /* lsp */   608,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_SIPtf */
        /* lsp */   480,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_GIPtf */
        /* lsp */   352,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_BMSK_ENTRY_TYPEtf */
        /* lsp */   349,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_BMSK_IPMC_TYPEtf */
        /* lsp */   348,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_BMSK_ROUNDtf */
        /* lsp */   347,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_BMSK_VIDtf */
        /* lsp */   320,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_BMSK_SIPtf */
        /* lsp */   192,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_BMSK_GIPtf */
        /* lsp */   64,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_HITtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_TTL_MINtf */
        /* lsp */   53,
        /* len */   8,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_MTU_MAX_IDXtf */
        /* lsp */   50,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_STACK_FWD_PMSKtf */
        /* lsp */   46,
        /* len */   4,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_VID_CMPtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_RPF_VIDtf */
        /* lsp */   33,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_L2_ENtf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_L2_ACTtf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_L2_MC_PMSK_IDXtf */
        /* lsp */   20,
        /* len */   10,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_L3_ENtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_L3_ACTtf */
        /* lsp */   17,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_RPF_CHK_ENtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_RPF_FAIL_ACTtf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_OIL_IDX_VALIDtf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_OIL_IDXtf */
        /* lsp */   4,
        /* len */   9,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_QOS_AStf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6MC_QOS_PRItf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_PREFIX_ROUTE_IP6UC_FIELDS[] =
{
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_VALIDtf */
        /* lsp */   351,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_ENTRY_TYPEtf */
        /* lsp */   349,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_IPtf */
        /* lsp */   192,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_BMSK_ENTRY_TYPEtf */
        /* lsp */   189,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_BMSK_IPtf */
        /* lsp */   32,
        /* len */   128,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_HITtf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_HOST_ROUTEtf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_DFLT_ROUTEtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_ACTIONtf */
        /* lsp */   18,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_NH_IDXtf */
        /* lsp */   7,
        /* len */   11,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_TTL_DECtf */
        /* lsp */   6,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_TTL_CHKtf */
        /* lsp */   5,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_DST_NULL_INTFtf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_QOS_AStf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IP6UC_QOS_PRItf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_PREFIX_ROUTE_IPMC_FIELDS[] =
{
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_VALIDtf */
        /* lsp */   639,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_ENTRY_TYPEtf */
        /* lsp */   637,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_IPMC_TYPEtf */
        /* lsp */   636,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_ROUNDtf */
        /* lsp */   635,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_VIDtf */
        /* lsp */   608,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_SIPtf */
        /* lsp */   480,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_GIPtf */
        /* lsp */   352,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_BMSK_ENTRY_TYPEtf */
        /* lsp */   349,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_BMSK_IPMC_TYPEtf */
        /* lsp */   348,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_BMSK_ROUNDtf */
        /* lsp */   347,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_BMSK_VIDtf */
        /* lsp */   320,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_BMSK_SIPtf */
        /* lsp */   192,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_BMSK_GIPtf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_HITtf */
        /* lsp */   61,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_TTL_MINtf */
        /* lsp */   53,
        /* len */   8,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_MTU_MAX_IDXtf */
        /* lsp */   50,
        /* len */   3,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_STACK_FWD_PMSKtf */
        /* lsp */   46,
        /* len */   4,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_VID_CMPtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_RPF_VIDtf */
        /* lsp */   33,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_L2_ENtf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_L2_ACTtf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_L2_MC_PMSK_IDXtf */
        /* lsp */   20,
        /* len */   10,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_L3_ENtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_L3_ACTtf */
        /* lsp */   17,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_RPF_CHK_ENtf */
        /* lsp */   16,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_RPF_FAIL_ACTtf */
        /* lsp */   14,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_OIL_IDX_VALIDtf */
        /* lsp */   13,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_OIL_IDXtf */
        /* lsp */   4,
        /* len */   9,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_QOS_AStf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPMC_QOS_PRItf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_PREFIX_ROUTE_IPUC_FIELDS[] =
{
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_VALIDtf */
        /* lsp */   351,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_ENTRY_TYPEtf */
        /* lsp */   349,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_IPtf */
        /* lsp */   192,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_BMSK_ENTRY_TYPEtf */
        /* lsp */   189,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_BMSK_IPtf */
        /* lsp */   32,
        /* len */   32,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_HITtf */
        /* lsp */   22,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_HOST_ROUTEtf */
        /* lsp */   21,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_DFLT_ROUTEtf */
        /* lsp */   20,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_ACTIONtf */
        /* lsp */   18,
        /* len */   2,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_NH_IDXtf */
        /* lsp */   7,
        /* len */   11,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_TTL_DECtf */
        /* lsp */   6,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_TTL_CHKtf */
        /* lsp */   5,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_DST_NULL_INTFtf */
        /* lsp */   4,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_QOS_AStf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_PREFIX_ROUTE_IPUC_QOS_PRItf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_L3_ROUTER_MAC_FIELDS[] =
{
    {   /* name     LONGAN_L3_ROUTER_MAC_VALIDtf */
        /* lsp */   212,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_PORT_TYPEtf */
        /* lsp */   211,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_PORT_IDtf */
        /* lsp */   205,
        /* len */   6,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_L3_INTFtf */
        /* lsp */   204,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_INTF_IDtf */
        /* lsp */   192,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_MACtf */
        /* lsp */   128,
        /* len */   48,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_BMSK_RESERVEDtf */
        /* lsp */   116,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_BMSK_PORT_TYPEtf */
        /* lsp */   115,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_BMSK_PORT_IDtf */
        /* lsp */   109,
        /* len */   6,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_BMSK_L3_INTFtf */
        /* lsp */   108,
        /* len */   1,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_BMSK_INTF_IDtf */
        /* lsp */   96,
        /* len */   12,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_BMSK_MACtf */
        /* lsp */   32,
        /* len */   48,
    },
    {   /* name     LONGAN_L3_ROUTER_MAC_ACTIONtf */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING */
#if defined(CONFIG_SDK_CHIP_FEATURE_ACL)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_IACL_FIELDS[] =
{
    {   /* name     LONGAN_IACL_FIELD_11tf */
        /* lsp */   592,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_10tf */
        /* lsp */   576,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_9tf */
        /* lsp */   560,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_8tf */
        /* lsp */   544,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_7tf */
        /* lsp */   528,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_6tf */
        /* lsp */   512,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_5tf */
        /* lsp */   496,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_4tf */
        /* lsp */   480,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_3tf */
        /* lsp */   464,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_2tf */
        /* lsp */   448,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_1tf */
        /* lsp */   432,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_FIELD_0tf */
        /* lsp */   416,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_STACKING_PORTtf */
        /* lsp */   415,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_SLPtf */
        /* lsp */   408,
        /* len */   7,
    },
    {   /* name     LONGAN_IACL_MGNT_VLANtf */
        /* lsp */   407,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_DEV_DMACtf */
        /* lsp */   406,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_NOT_FIRST_FRAGtf */
        /* lsp */   405,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_FRAME_TYPE_L4tf */
        /* lsp */   402,
        /* len */   3,
    },
    {   /* name     LONGAN_IACL_FRAME_TYPEtf */
        /* lsp */   400,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_OUTER_UNTAG_PRITAGtf */
        /* lsp */   399,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_INNER_UNTAG_PRITAGtf */
        /* lsp */   398,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_OUTER_TAG_PRITAGtf */
        /* lsp */   397,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_INNER_TAG_PRITAGtf */
        /* lsp */   396,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_FRAME_TYPE_L2tf */
        /* lsp */   394,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_IGR_NML_PORTtf */
        /* lsp */   393,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_TIDtf */
        /* lsp */   392,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_11tf */
        /* lsp */   376,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_10tf */
        /* lsp */   360,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_9tf */
        /* lsp */   344,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_8tf */
        /* lsp */   328,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_7tf */
        /* lsp */   312,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_6tf */
        /* lsp */   296,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_5tf */
        /* lsp */   280,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_4tf */
        /* lsp */   264,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_3tf */
        /* lsp */   248,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_2tf */
        /* lsp */   232,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_1tf */
        /* lsp */   216,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_FIELD_0tf */
        /* lsp */   200,
        /* len */   16,
    },
    {   /* name     LONGAN_IACL_BMSK_STACKING_PORTtf */
        /* lsp */   199,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_SLPtf */
        /* lsp */   192,
        /* len */   7,
    },
    {   /* name     LONGAN_IACL_BMSK_MGNT_VLANtf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_DEV_DMACtf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_NOT_FIRST_FRAGtf */
        /* lsp */   189,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_FRAME_TYPE_L4tf */
        /* lsp */   186,
        /* len */   3,
    },
    {   /* name     LONGAN_IACL_BMSK_FRAME_TYPEtf */
        /* lsp */   184,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_BMSK_OUTER_UNTAG_PRITAGtf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_INNER_UNTAG_PRITAGtf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_OUTER_TAG_PRITAGtf */
        /* lsp */   181,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_INNER_TAG_PRITAGtf */
        /* lsp */   180,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_FRAME_TYPE_L2tf */
        /* lsp */   178,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_BMSK_IGR_NML_PORTtf */
        /* lsp */   177,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_BMSK_TIDtf */
        /* lsp */   176,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_VALIDtf */
        /* lsp */   175,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_NOTtf */
        /* lsp */   174,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_AND1tf */
        /* lsp */   173,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_AND2tf */
        /* lsp */   172,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_INVERT_IP_RSVD_FLAGtf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_RED_REMARKtf */
        /* lsp */   170,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_YELLOW_REMARKtf */
        /* lsp */   169,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_REMARKtf */
        /* lsp */   168,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_CPUQIDtf */
        /* lsp */   167,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_METADATAtf */
        /* lsp */   166,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_BYPASStf */
        /* lsp */   165,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_PRIORITYtf */
        /* lsp */   164,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_TAG_STATUStf */
        /* lsp */   163,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_OPRItf */
        /* lsp */   162,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_OVLANtf */
        /* lsp */   161,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_IPRItf */
        /* lsp */   160,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_IVLANtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_METERtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_MIRRORtf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_LOGtf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_FWDtf */
        /* lsp */   155,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_RED_DROPtf */
        /* lsp */   154,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_YELLOW_DROPtf */
        /* lsp */   153,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_ACT_MSK_DROPtf */
        /* lsp */   152,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_DROP_ACTtf */
        /* lsp */   151,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_YELLOW_DROP_ACTtf */
        /* lsp */   150,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_RED_DROP_ACTtf */
        /* lsp */   149,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_FWD_ACTtf */
        /* lsp */   146,
        /* len */   3,
    },
    {   /* name     LONGAN_IACL_FWD_CPU_PKT_FMTtf */
        /* lsp */   144,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_FWD_SELtf */
        /* lsp */   142,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_FWD_PORT_INFOtf */
        /* lsp */   131,
        /* len */   11,
    },
    {   /* name     LONGAN_IACL_LOG_ACTtf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_METER_INDEXtf */
        /* lsp */   119,
        /* len */   8,
    },
    {   /* name     LONGAN_IACL_IVLAN_VID_ACTtf */
        /* lsp */   117,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_IVLAN_VIDtf */
        /* lsp */   105,
        /* len */   12,
    },
    {   /* name     LONGAN_IACL_IVLAN_TPID_ACTtf */
        /* lsp */   104,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_IVLAN_TPID_IDXtf */
        /* lsp */   102,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_IVLAN_PRI_ACTtf */
        /* lsp */   99,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_IVLAN_PRItf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     LONGAN_IACL_OVLAN_VID_ACTtf */
        /* lsp */   94,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_OVLAN_VIDtf */
        /* lsp */   82,
        /* len */   12,
    },
    {   /* name     LONGAN_IACL_OVLAN_TPID_ACTtf */
        /* lsp */   81,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_OVLAN_TPID_IDXtf */
        /* lsp */   79,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_OVLAN_PRI_ACTtf */
        /* lsp */   77,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_OVLAN_PRItf */
        /* lsp */   74,
        /* len */   3,
    },
    {   /* name     LONGAN_IACL_MIRROR_ACTtf */
        /* lsp */   72,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_MIRROR_INDEXtf */
        /* lsp */   70,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_TAG_STATUS_INNERtf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_TAG_STATUS_OUTERtf */
        /* lsp */   60,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_PRI_DATAtf */
        /* lsp */   57,
        /* len */   3,
    },
    {   /* name     LONGAN_IACL_QID_DATAtf */
        /* lsp */   52,
        /* len */   5,
    },
    {   /* name     LONGAN_IACL_BYPASS_DATAtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     LONGAN_IACL_META_DATAtf */
        /* lsp */   40,
        /* len */   8,
    },
    {   /* name     LONGAN_IACL_REMARK_ACTtf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_REMARK_VALUEtf */
        /* lsp */   22,
        /* len */   8,
    },
    {   /* name     LONGAN_IACL_YELLOW_REMARK_ACTtf */
        /* lsp */   20,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_YELLOW_REMARK_VALUEtf */
        /* lsp */   12,
        /* len */   8,
    },
    {   /* name     LONGAN_IACL_RED_REMARK_ACTtf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     LONGAN_IACL_RED_REMARK_VALUEtf */
        /* lsp */   2,
        /* len */   8,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_LOG_FIELDS[] =
{
    {   /* name     LONGAN_LOG_COUNTERtf */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_VACL_FIELDS[] =
{
    {   /* name     LONGAN_VACL_FIELD_11tf */
        /* lsp */   592,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_10tf */
        /* lsp */   576,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_9tf */
        /* lsp */   560,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_8tf */
        /* lsp */   544,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_7tf */
        /* lsp */   528,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_6tf */
        /* lsp */   512,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_5tf */
        /* lsp */   496,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_4tf */
        /* lsp */   480,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_3tf */
        /* lsp */   464,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_2tf */
        /* lsp */   448,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_1tf */
        /* lsp */   432,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_FIELD_0tf */
        /* lsp */   416,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_STACKING_PORTtf */
        /* lsp */   415,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_SLPtf */
        /* lsp */   408,
        /* len */   7,
    },
    {   /* name     LONGAN_VACL_MGNT_VLANtf */
        /* lsp */   407,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_CONTENT_TOO_DEEPtf */
        /* lsp */   406,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_NOT_FIRST_FRAGtf */
        /* lsp */   405,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_FRAME_TYPE_L4tf */
        /* lsp */   402,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_FRAME_TYPEtf */
        /* lsp */   400,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_OUTER_UNTAG_PRITAGtf */
        /* lsp */   399,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_INNER_UNTAG_PRITAGtf */
        /* lsp */   398,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_OUTER_TAG_PRITAGtf */
        /* lsp */   397,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_INNER_TAG_PRITAGtf */
        /* lsp */   396,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_FRAME_TYPE_L2tf */
        /* lsp */   394,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_IGR_NML_PORTtf */
        /* lsp */   393,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_TIDtf */
        /* lsp */   392,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_11tf */
        /* lsp */   376,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_10tf */
        /* lsp */   360,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_9tf */
        /* lsp */   344,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_8tf */
        /* lsp */   328,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_7tf */
        /* lsp */   312,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_6tf */
        /* lsp */   296,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_5tf */
        /* lsp */   280,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_4tf */
        /* lsp */   264,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_3tf */
        /* lsp */   248,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_2tf */
        /* lsp */   232,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_1tf */
        /* lsp */   216,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_FIELD_0tf */
        /* lsp */   200,
        /* len */   16,
    },
    {   /* name     LONGAN_VACL_BMSK_STACKING_PORTtf */
        /* lsp */   199,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_SLPtf */
        /* lsp */   192,
        /* len */   7,
    },
    {   /* name     LONGAN_VACL_BMSK_MGNT_VLANtf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_CONTENT_TOO_DEEPtf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_NOT_FIRST_FRAGtf */
        /* lsp */   189,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_FRAME_TYPE_L4tf */
        /* lsp */   186,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_BMSK_FRAME_TYPEtf */
        /* lsp */   184,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_BMSK_OUTER_UNTAG_PRITAGtf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_INNER_UNTAG_PRITAGtf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_OUTER_TAG_PRITAGtf */
        /* lsp */   181,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_INNER_TAG_PRITAGtf */
        /* lsp */   180,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_FRAME_TYPE_L2tf */
        /* lsp */   178,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_BMSK_IGR_NML_PORTtf */
        /* lsp */   177,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_BMSK_TIDtf */
        /* lsp */   176,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_VALIDtf */
        /* lsp */   175,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_NOTtf */
        /* lsp */   174,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_AND1tf */
        /* lsp */   173,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_AND2tf */
        /* lsp */   172,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_INVERT_IP_RSVD_FLAGtf */
        /* lsp */   171,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_RED_REMARKtf */
        /* lsp */   170,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_YELLOW_REMARKtf */
        /* lsp */   169,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_REMARKtf */
        /* lsp */   168,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_QIDtf */
        /* lsp */   167,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_METADATAtf */
        /* lsp */   166,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_BYPASStf */
        /* lsp */   165,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_PRIORITYtf */
        /* lsp */   164,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_TAG_STATUStf */
        /* lsp */   163,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_OPRItf */
        /* lsp */   162,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_OVLANtf */
        /* lsp */   161,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_IPRItf */
        /* lsp */   160,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_IVLANtf */
        /* lsp */   159,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_METERtf */
        /* lsp */   158,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_MIRRORtf */
        /* lsp */   157,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_LOGtf */
        /* lsp */   156,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_FWDtf */
        /* lsp */   155,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_RED_DROPtf */
        /* lsp */   154,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_YELLOW_DROPtf */
        /* lsp */   153,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_ACT_MSK_DROPtf */
        /* lsp */   152,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_DROP_ACTtf */
        /* lsp */   151,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_YELLOW_DROP_ACTtf */
        /* lsp */   150,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_RED_DROP_ACTtf */
        /* lsp */   149,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_FWD_ACTtf */
        /* lsp */   146,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_FWD_CPU_PKT_FMTtf */
        /* lsp */   144,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_FWD_SA_LRNtf */
        /* lsp */   143,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_FWD_SELtf */
        /* lsp */   142,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_FWD_PORT_INFOtf */
        /* lsp */   131,
        /* len */   11,
    },
    {   /* name     LONGAN_VACL_LOG_ACTtf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_METER_INDEXtf */
        /* lsp */   119,
        /* len */   8,
    },
    {   /* name     LONGAN_VACL_IVLAN_VID_ACTtf */
        /* lsp */   117,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_IVLAN_VIDtf */
        /* lsp */   105,
        /* len */   12,
    },
    {   /* name     LONGAN_VACL_IVLAN_PRI_ACTtf */
        /* lsp */   99,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_IVLAN_PRItf */
        /* lsp */   96,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_OVLAN_VID_ACTtf */
        /* lsp */   94,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_OVLAN_VIDtf */
        /* lsp */   82,
        /* len */   12,
    },
    {   /* name     LONGAN_VACL_OVLAN_PRI_ACTtf */
        /* lsp */   77,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_OVLAN_PRItf */
        /* lsp */   74,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_MIRROR_ACTtf */
        /* lsp */   73,
        /* len */   1,
    },
    {   /* name     LONGAN_VACL_MIRROR_INDEXtf */
        /* lsp */   70,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_TAG_STATUS_INNERtf */
        /* lsp */   62,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_TAG_STATUS_OUTERtf */
        /* lsp */   60,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_INTERNAL_PRItf */
        /* lsp */   57,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_QID_DATAtf */
        /* lsp */   52,
        /* len */   5,
    },
    {   /* name     LONGAN_VACL_BYPASS_DATAtf */
        /* lsp */   48,
        /* len */   3,
    },
    {   /* name     LONGAN_VACL_META_DATAtf */
        /* lsp */   40,
        /* len */   8,
    },
    {   /* name     LONGAN_VACL_REMARK_ACTtf */
        /* lsp */   30,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_REMARK_VALUEtf */
        /* lsp */   22,
        /* len */   8,
    },
    {   /* name     LONGAN_VACL_YELLOW_REMARK_ACTtf */
        /* lsp */   20,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_YELLOW_REMARK_VALUEtf */
        /* lsp */   12,
        /* len */   8,
    },
    {   /* name     LONGAN_VACL_RED_REMARK_ACTtf */
        /* lsp */   10,
        /* len */   2,
    },
    {   /* name     LONGAN_VACL_RED_REMARK_VALUEtf */
        /* lsp */   2,
        /* len */   8,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_ACL */
#if defined(CONFIG_SDK_CHIP_FEATURE_PARSER_HSB)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_HSB_FIELDS[] =
{
    {   /* name     LONGAN_HSB_PAGE_CNTtf */
        /* lsp */   954,
        /* len */   6,
    },
    {   /* name     LONGAN_HSB_LST_DSCtf */
        /* lsp */   942,
        /* len */   12,
    },
    {   /* name     LONGAN_HSB_FST_DSCtf */
        /* lsp */   930,
        /* len */   12,
    },
    {   /* name     LONGAN_HSB_LBHDR_VLDtf */
        /* lsp */   929,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_STHDR_VLDtf */
        /* lsp */   928,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_STHDR_0_3tf */
        /* lsp */   896,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_STHDR_4_7tf */
        /* lsp */   864,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_STHDR_8_11tf */
        /* lsp */   832,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_STHDR_12_15tf */
        /* lsp */   800,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_STHDR_16tf */
        /* lsp */   768,
        /* len */   8,
    },
    {   /* name     LONGAN_HSB_FS11_DATAtf */
        /* lsp */   752,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS10_DATAtf */
        /* lsp */   736,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS9_DATAtf */
        /* lsp */   720,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS8_DATAtf */
        /* lsp */   704,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS7_DATAtf */
        /* lsp */   688,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS6_DATAtf */
        /* lsp */   672,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS5_DATAtf */
        /* lsp */   656,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS4_DATAtf */
        /* lsp */   640,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS3_DATAtf */
        /* lsp */   624,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS2_DATAtf */
        /* lsp */   608,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS1_DATAtf */
        /* lsp */   592,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS0_DATAtf */
        /* lsp */   576,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_FS_VALIDtf */
        /* lsp */   564,
        /* len */   12,
    },
    {   /* name     LONGAN_HSB_IPV6_FLOW_LABELtf */
        /* lsp */   544,
        /* len */   20,
    },
    {   /* name     LONGAN_HSB_INGR_ERRtf */
        /* lsp */   538,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_UDP_PTPtf */
        /* lsp */   537,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_L2_PTPtf */
        /* lsp */   536,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_DSAP_SSAPtf */
        /* lsp */   512,
        /* len */   24,
    },
    {   /* name     LONGAN_HSB_ARP_OPCODEtf */
        /* lsp */   480,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_TGT_MAC_47_16tf */
        /* lsp */   448,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_TGT_MAC_15_0tf */
        /* lsp */   432,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_SENDER_MAC_47_32tf */
        /* lsp */   416,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_SENDER_MAC_31_0tf */
        /* lsp */   384,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_DPORTtf */
        /* lsp */   368,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_SPORTtf */
        /* lsp */   352,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_TCP_FLAGtf */
        /* lsp */   344,
        /* len */   8,
    },
    {   /* name     LONGAN_HSB_IP_TTLtf */
        /* lsp */   336,
        /* len */   8,
    },
    {   /* name     LONGAN_HSB_IP_TOStf */
        /* lsp */   328,
        /* len */   8,
    },
    {   /* name     LONGAN_HSB_IP_PROTOCOLtf */
        /* lsp */   320,
        /* len */   8,
    },
    {   /* name     LONGAN_HSB_IP_VERtf */
        /* lsp */   304,
        /* len */   4,
    },
    {   /* name     LONGAN_HSB_IP_FLAGtf */
        /* lsp */   301,
        /* len */   3,
    },
    {   /* name     LONGAN_HSB_IP_OFFSETtf */
        /* lsp */   288,
        /* len */   13,
    },
    {   /* name     LONGAN_HSB_DIPtf */
        /* lsp */   256,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_SIPtf */
        /* lsp */   224,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_OTAG_CONTENTtf */
        /* lsp */   208,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_ITAG_CONTENTtf */
        /* lsp */   192,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_TYPELENtf */
        /* lsp */   176,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_IP_LENGTHtf */
        /* lsp */   160,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_SMAC_47_16tf */
        /* lsp */   128,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_SMAC_15_0tf */
        /* lsp */   112,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_DMAC_47_32tf */
        /* lsp */   96,
        /* len */   16,
    },
    {   /* name     LONGAN_HSB_DMAC_31_0tf */
        /* lsp */   64,
        /* len */   32,
    },
    {   /* name     LONGAN_HSB_OTPID_IDXtf */
        /* lsp */   58,
        /* len */   2,
    },
    {   /* name     LONGAN_HSB_ITPID_IDXtf */
        /* lsp */   56,
        /* len */   2,
    },
    {   /* name     LONGAN_HSB_IPV4_HDRLENtf */
        /* lsp */   52,
        /* len */   4,
    },
    {   /* name     LONGAN_HSB_TCP_SN_EQ_0tf */
        /* lsp */   51,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_HOPtf */
        /* lsp */   50,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_ROUTtf */
        /* lsp */   49,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_FRAGtf */
        /* lsp */   48,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_DESTtf */
        /* lsp */   47,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_AUTHtf */
        /* lsp */   46,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV4_CHKSUM_OKtf */
        /* lsp */   45,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_EXT_LONGtf */
        /* lsp */   44,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV6_PKTtf */
        /* lsp */   43,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_IPV4_PKTtf */
        /* lsp */   42,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_RTAG_TYPEtf */
        /* lsp */   41,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_RTAG_EXISTtf */
        /* lsp */   40,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_ETAG_EXISTtf */
        /* lsp */   39,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_CTAG_EXISTtf */
        /* lsp */   38,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_OTAG_EXISTtf */
        /* lsp */   37,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_ITAG_EXISTtf */
        /* lsp */   36,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_OAM_PDUtf */
        /* lsp */   35,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_LLC_OTHERtf */
        /* lsp */   34,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_PPPOE_PKTtf */
        /* lsp */   33,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_RFC1042tf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_SPAtf */
        /* lsp */   16,
        /* len */   6,
    },
    {   /* name     LONGAN_HSB_L2_ERR_PKTtf */
        /* lsp */   15,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_L4_HDR_CHKtf */
        /* lsp */   14,
        /* len */   1,
    },
    {   /* name     LONGAN_HSB_PKT_LENtf */
        /* lsp */   0,
        /* len */   14,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PARSER_HSB */
#if defined(CONFIG_SDK_CHIP_FEATURE_MODIFIER_HSA)
#if defined(CONFIG_SDK_RTL9300)
rtk_tableField_t RTL9300_HSA_FIELDS[] =
{
    {   /* name     LONGAN_HSA_DROP_RSNtf */
        /* lsp */   684,
        /* len */   7,
    },
    {   /* name     LONGAN_HSA_FST_DSCtf */
        /* lsp */   672,
        /* len */   12,
    },
    {   /* name     LONGAN_HSA_TXQID_STK_PORTtf */
        /* lsp */   648,
        /* len */   16,
    },
    {   /* name     LONGAN_HSA_TXQID_NORMAL_71_64tf */
        /* lsp */   640,
        /* len */   8,
    },
    {   /* name     LONGAN_HSA_TXQID_NORMAL_63_32tf */
        /* lsp */   608,
        /* len */   32,
    },
    {   /* name     LONGAN_HSA_TXQID_NORMAL_31_0tf */
        /* lsp */   576,
        /* len */   32,
    },
    {   /* name     LONGAN_HSA_DPM_LBtf */
        /* lsp */   573,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_DPMtf */
        /* lsp */   544,
        /* len */   29,
    },
    {   /* name     LONGAN_HSA_REPLICATE_LST_CPtf */
        /* lsp */   529,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_REPLICATE_FST_CPtf */
        /* lsp */   528,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_REPLICATE_NONEtf */
        /* lsp */   527,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_REPLICATE_TYPEtf */
        /* lsp */   525,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_SFLOW_SMPL_PORTtf */
        /* lsp */   522,
        /* len */   3,
    },
    {   /* name     LONGAN_HSA_SFLOW_INFOtf */
        /* lsp */   517,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_SFLOW_NOR_FWDtf */
        /* lsp */   516,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_STK_NOR_FWDtf */
        /* lsp */   512,
        /* len */   4,
    },
    {   /* name     LONGAN_HSA_STK_CPU_FWDtf */
        /* lsp */   505,
        /* len */   4,
    },
    {   /* name     LONGAN_HSA_MIRING_PORT_3tf */
        /* lsp */   500,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIRING_PORT_2tf */
        /* lsp */   495,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIRING_PORT_1tf */
        /* lsp */   490,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIRING_PORT_0tf */
        /* lsp */   485,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIR3_INFOtf */
        /* lsp */   480,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIR2_INFOtf */
        /* lsp */   474,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIR1_INFOtf */
        /* lsp */   469,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIR0_INFOtf */
        /* lsp */   464,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_MIR_NORMAL_FWDtf */
        /* lsp */   460,
        /* len */   4,
    },
    {   /* name     LONGAN_HSA_DY_GASPtf */
        /* lsp */   459,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_DPCtf */
        /* lsp */   454,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_PAGE_CNTtf */
        /* lsp */   448,
        /* len */   6,
    },
    {   /* name     LONGAN_HSA_PKT_LENtf */
        /* lsp */   430,
        /* len */   14,
    },
    {   /* name     LONGAN_HSA_LST_DSCtf */
        /* lsp */   418,
        /* len */   12,
    },
    {   /* name     LONGAN_HSA_IPMC_QIDtf */
        /* lsp */   417,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IPMC_PKTtf */
        /* lsp */   416,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_NOR_CPU_SELtf */
        /* lsp */   404,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_TXQID_CPUtf */
        /* lsp */   399,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_LB_PKTtf */
        /* lsp */   398,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IP_RSVD_INVERTtf */
        /* lsp */   397,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_DA_HITtf */
        /* lsp */   396,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_STK_MIRtf */
        /* lsp */   395,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_LB_TTLtf */
        /* lsp */   392,
        /* len */   3,
    },
    {   /* name     LONGAN_HSA_META_DATAtf */
        /* lsp */   384,
        /* len */   8,
    },
    {   /* name     LONGAN_HSA_CTX_L3_ACTtf */
        /* lsp */   377,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_ACL_ACTtf */
        /* lsp */   376,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_CNGST_DROPtf */
        /* lsp */   375,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_BP_FLTR_EGRtf */
        /* lsp */   374,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_BP_STP_EGRtf */
        /* lsp */   373,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_BP_VLAN_EGRtf */
        /* lsp */   372,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_QIDtf */
        /* lsp */   367,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_CTX_AS_QIDtf */
        /* lsp */   366,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_SRC_FLTR_ENtf */
        /* lsp */   365,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_FWD_VID_ENtf */
        /* lsp */   364,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_SPNtf */
        /* lsp */   354,
        /* len */   10,
    },
    {   /* name     LONGAN_HSA_CTX_SPN_IS_TRKtf */
        /* lsp */   353,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_SP_FLTR_ENtf */
        /* lsp */   352,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTX_DPM_28_55tf */
        /* lsp */   320,
        /* len */   28,
    },
    {   /* name     LONGAN_HSA_CTX_DPM_0_27tf */
        /* lsp */   292,
        /* len */   28,
    },
    {   /* name     LONGAN_HSA_CTX_DEV_IDtf */
        /* lsp */   288,
        /* len */   4,
    },
    {   /* name     LONGAN_HSA_CTX_FWD_TYPEtf */
        /* lsp */   284,
        /* len */   4,
    },
    {   /* name     LONGAN_HSA_DP_INFOtf */
        /* lsp */   272,
        /* len */   12,
    },
    {   /* name     LONGAN_HSA_DP_FMTtf */
        /* lsp */   271,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_FWD_TYPEtf */
        /* lsp */   269,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_SA_LRNtf */
        /* lsp */   268,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_VB_ISO_MBRtf */
        /* lsp */   267,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_TRK_HASHtf */
        /* lsp */   261,
        /* len */   6,
    },
    {   /* name     LONGAN_HSA_NEW_SAtf */
        /* lsp */   260,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L2_MAC_CSTtf */
        /* lsp */   259,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_PMV_FORBIDtf */
        /* lsp */   258,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L2_DYN_PMVtf */
        /* lsp */   257,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L2_STTC_PMVtf */
        /* lsp */   256,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L2_ORG_PORTtf */
        /* lsp */   246,
        /* len */   10,
    },
    {   /* name     LONGAN_HSA_L2_ORG_TRK_IFtf */
        /* lsp */   245,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_ATK_TYPEtf */
        /* lsp */   240,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_ACL_IDXtf */
        /* lsp */   225,
        /* len */   15,
    },
    {   /* name     LONGAN_HSA_ACL_HITtf */
        /* lsp */   224,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IS_EAV_Atf */
        /* lsp */   216,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IS_EAV_Btf */
        /* lsp */   215,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_REASONtf */
        /* lsp */   209,
        /* len */   6,
    },
    {   /* name     LONGAN_HSA_INT_DSCP_HITtf */
        /* lsp */   208,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_INT_DSCPtf */
        /* lsp */   200,
        /* len */   8,
    },
    {   /* name     LONGAN_HSA_INT_PRItf */
        /* lsp */   197,
        /* len */   3,
    },
    {   /* name     LONGAN_HSA_EACL_OPRI_AStf */
        /* lsp */   196,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_EACL_IPRI_AStf */
        /* lsp */   195,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IACL_OPRI_AStf */
        /* lsp */   194,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IACL_IPRI_AStf */
        /* lsp */   193,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CPU_TAGSTS_AStf */
        /* lsp */   192,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_EACL_ITAG_STATUS_AStf */
        /* lsp */   191,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_EACL_OTAG_STATUS_AStf */
        /* lsp */   190,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IACL_ITAG_STATUS_AStf */
        /* lsp */   189,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IACL_OTAG_STATUS_AStf */
        /* lsp */   188,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_ALE_ITAG_STATUStf */
        /* lsp */   186,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_ALE_OTAG_STATUStf */
        /* lsp */   184,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_IACL_OTPID_AStf */
        /* lsp */   183,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IACL_ITPID_AStf */
        /* lsp */   182,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_EACL_OTPID_AStf */
        /* lsp */   181,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_EACL_ITPID_AStf */
        /* lsp */   180,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_OTPID_IDXtf */
        /* lsp */   178,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_ITPID_IDXtf */
        /* lsp */   176,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_ALE_OTAG_CONTENTtf */
        /* lsp */   160,
        /* len */   16,
    },
    {   /* name     LONGAN_HSA_ALE_ITAG_CONTENTtf */
        /* lsp */   129,
        /* len */   16,
    },
    {   /* name     LONGAN_HSA_EACL_IVID_AStf */
        /* lsp */   128,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_EACL_OVID_AStf */
        /* lsp */   127,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_N_1_OVID_AStf */
        /* lsp */   126,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_N_1_IVID_AStf */
        /* lsp */   125,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_TTL_DECtf */
        /* lsp */   124,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L2_HASH_FULLtf */
        /* lsp */   123,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_INVALID_SAtf */
        /* lsp */   122,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_ROUTED_PKTtf */
        /* lsp */   121,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CPU_FMT_ENtf */
        /* lsp */   120,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CPU_FMTtf */
        /* lsp */   119,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L3_SA_IDXtf */
        /* lsp */   113,
        /* len */   6,
    },
    {   /* name     LONGAN_HSA_L3_DA_IDXtf */
        /* lsp */   102,
        /* len */   11,
    },
    {   /* name     LONGAN_HSA_L3_SA_IFtf */
        /* lsp */   101,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L3_DA_IFtf */
        /* lsp */   100,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_OAM_SWAP_MACtf */
        /* lsp */   99,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_DPtf */
        /* lsp */   97,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_RVID_BASEtf */
        /* lsp */   96,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_FWD_VIDtf */
        /* lsp */   84,
        /* len */   12,
    },
    {   /* name     LONGAN_HSA_ORG_OTPID_IDXtf */
        /* lsp */   82,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_ORG_ITPID_IDXtf */
        /* lsp */   80,
        /* len */   2,
    },
    {   /* name     LONGAN_HSA_ORG_OTAG_CONTENTtf */
        /* lsp */   64,
        /* len */   16,
    },
    {   /* name     LONGAN_HSA_ORG_ITAG_CONTENTtf */
        /* lsp */   33,
        /* len */   16,
    },
    {   /* name     LONGAN_HSA_ETAG_IFtf */
        /* lsp */   32,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_CTAG_IFtf */
        /* lsp */   31,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_ORG_OTAG_IFtf */
        /* lsp */   30,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_ORG_ITAG_IFtf */
        /* lsp */   29,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_PPPOE_IFtf */
        /* lsp */   28,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_LLC_OTHERtf */
        /* lsp */   27,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_RFC1042tf */
        /* lsp */   26,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_STK_SPA_TRK_IDtf */
        /* lsp */   20,
        /* len */   6,
    },
    {   /* name     LONGAN_HSA_STK_SPA_IS_TRKtf */
        /* lsp */   19,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_STK_SPAtf */
        /* lsp */   13,
        /* len */   6,
    },
    {   /* name     LONGAN_HSA_STK_SDEVtf */
        /* lsp */   9,
        /* len */   4,
    },
    {   /* name     LONGAN_HSA_SPHYtf */
        /* lsp */   4,
        /* len */   5,
    },
    {   /* name     LONGAN_HSA_L2_ERR_PKTtf */
        /* lsp */   3,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_L3_ERR_PKTtf */
        /* lsp */   2,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IPV6_PKTtf */
        /* lsp */   1,
        /* len */   1,
    },
    {   /* name     LONGAN_HSA_IPV4_PKTtf */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MODIFIER_HSA */

